Improvements to SFP.
libcsp/libcsp pull request #110
Opened 2017-09-27 14:00 UTC by mtl

This commit addresses the following issues:

1. sfp_send_\*() leaves the connection with CSP_FFRAG set, which results in malformed packets (FRAG flag set but no sfp_header in the packet) if the connection is later reused for non-SFP traffic.
2. Resolves ambiguity over whether the caller to sfp_recv_\*() must invoke csp_free() on dataout when the return value is -1 and dataout is non-NULL.
3. Resolves ambiguity over whether csp_buffer_free has been called on the packet when the return value is -1. Note that this may cause a problem if the caller expects to perform subsequent diagnostics on the invalid packet. However, other failures do free the packet, so without this change the caller would not know the reason for the error (all failures return -1) and thus whether the packet has been freed. If diagnostics are required in this case (i.e., sfp_recv_\*() called on a packet with CSP_FFRAG clear), the caller can check for CSP_FFRAG prior to invoking sfp_recv_\*() and avoid the error.

2018-01-24 07:08 UTC, johandc approved these changes

2018-01-24 07:08 UTC, johandc commented on src/csp_sfp.c
> +		conn->idout.flags &= ~CSP_FFRAG; /* Clear fragment flag */
I feel like this is something best solved in csp_conn_new()

2018-01-24 07:08 UTC, johandc commented on src/csp_sfp.c
> +	*dataout = NULL; /* Allow caller to assume csp_free() can always be called when dataout is non-NULL */
agreed

2018-01-24 07:08 UTC, johandc commented on src/csp_sfp.c
> +			csp_buffer_free(packet); /* Always free the packet */
This looks like a regular memory leak, thanks for finding this. However we could do without the comment.

2018-01-24 07:14 UTC, johandc commented on src/csp_sfp.c
> +		conn->idout.flags &= ~CSP_FFRAG; /* Clear fragment flag */
In fact, after checking, i can see that this is handled in csp_conn_new, or rather in the csp_connect call. 

So the answer would be, that do not reuse a connection. It's better to call csp_close() on the SFP connection and csp_connect() to open up a new one.

So my revised answer is, that this line should be omitted, and the connection reuse should be changed/fixed instead.

2018-01-24 07:17 UTC, johandc requested changes
I was too quick to approve, after looking at it again, i would like the change in csp_sfp.c to be revised.

2018-01-24 22:06 UTC, mtl commented on src/csp_sfp.c
> +		conn->idout.flags &= ~CSP_FFRAG; /* Clear fragment flag */
Ok, this change is backed out in 2a7b3114d03906d673082ea28eba98677a295d50.

2018-01-24 22:06 UTC, mtl commented on src/csp_sfp.c
> +			csp_buffer_free(packet); /* Always free the packet */
Comment removed in 2a7b3114d03906d673082ea28eba98677a295d50. Thanks.

2018-03-19 12:43 UTC, johandc approved these changes

2018-03-19 12:43 UTC, merged