Updated init, interfaces and examples
libcsp/libcsp pull request #147
Opened 2020-02-06 17:49 UTC by perwulff

First of, sorry for the number of commits in a single request - but all changes ties into the example code.

- Moved csp_buffer_init() into csp_init().
- ZMQ interface:
  - Added parameter for returning the added csp_iface_t
  - Added 'flags' parameter for future support of setting options on a ZMQ connection, e.g. alive.
- Removed unused rtable functions: csp_rtable_find_iface()/csp_rtable_finc_mac()
- Scoped usart with csp and consolidated code for Windows and Linux implementation.
- Updated example code
  - Updated example code to a single csp_server_client.c implementation, which can be run standalone or as separate server and client node, communicating through zmqproxy.
  - Added examples/csp_arch.c, which runs a number of simple test on most cross-platform APIs. Travis runs the same code on LInux, Mac and Windows.

2020-02-06 18:46 UTC, johandc commented on src/bindings/python/pycsp.c
> +        return NULL; // TypeError is thrownfcsp_init
Typo

2020-02-06 18:50 UTC, johandc requested changes

2020-02-06 18:50 UTC, johandc commented on src/csp_buffer.c
> +	csp_buffer_pool = csp_calloc(csp_conf.buffers, skbfsize);
I think we want to use malloc. Not calloc.
All buffers are considered dirty when gotten.
The extra cost of clearing out all buffers can increase boot time on small systems

2020-02-07 14:08 UTC, perwulff commented on src/bindings/python/pycsp.c
> +        return NULL; // TypeError is thrownfcsp_init
Fixed for now - a larger binding update will follow soon.

2020-02-07 14:09 UTC, perwulff commented on src/bindings/python/pycsp.c
> +        return NULL; // TypeError is thrownfcsp_init
Changed to malloc - and set ref_count to1 instead of ++.

2020-02-07 14:09 UTC, perwulff commented on src/csp_buffer.c
> +	csp_buffer_pool = csp_calloc(csp_conf.buffers, skbfsize);
Fixed for now - a larger binding update will follow soon.

2020-02-08 21:17 UTC, johandc approved these changes

2020-02-11 08:24 UTC, merged