Add support for RIOT OS
libcsp/libcsp pull request #167
Opened 2020-08-19 09:07 UTC by pi76r

Added [RIOT OS](https://github.com/RIOT-OS/RIOT) to libcsp, similar to [FreeRTOS](https://www.freertos.org/), only for the CAN bus.

Here is the list of modification:
- Add `riotos` to the waf build system, and in the examples
- Add `src/arch/riotos`
- Rename `src/drivers/can/can_socketcan.c` to `src/drivers/can/can_linux.c` to support other can drivers
- Add `src/drivers/can/can_riotos.c`
- Few changes to make libcsp compatible with arm-none-eabi-gcc

Now the driver can be selected at build time with the option `--with-driver-can=<linux | riotos>`

The implementation of the semaphore is not perfect, it does not fully pass csp_arch but csp_server_client works fine.

2020-08-19 21:16 UTC, johandc requested changes
Hi, this looks fine.
Im pussled over the usage of stings.h
I don't know how I feel about changing the build configuration and the socketcan rename. It would break a lot of Linux builds for no reason other than a name change I think.
Maybe it was cleaner if each driver would just have their own option to enable or disable it. 
Finally CSP 2.0 is coming out. We may consider merging the riotos stuff for that one.
You can try it out (see the 2.0 pull request)

2020-08-19 21:16 UTC, johandc commented on src/csp_iflist.c
Why not use the more portable string.h?

2020-08-19 21:16 UTC, johandc commented on src/rtable/csp_rtable.c
> +
Again, why is this needed? We build with that toolchain too, and have never needed anything from strings.h

2020-08-19 21:16 UTC, johandc commented on wscript
> +valid_os = ['posix', 'windows', 'freertos', 'macosx', 'riotos']
CSP will also support the meson build system in v2.0 but it should be very easy to add to that too.

2020-08-19 21:16 UTC, johandc commented on src/drivers/can/can_riotos.c
> +#include "tja1042.h"
Who provides this header?

2020-08-19 21:30 UTC, johandc commented
We did away with platform.h

2020-08-20 08:05 UTC, pi76r commented on src/csp_iflist.c
You are right we can use string.h, and when using arm-none-eabi-gcc, the flag `_POSIX_C_SOURCE=200809L` must be set before the inclusion of string.h, otherwise function like `strnlen`, `strtok_r` and `strcasecmp` cannot be found.  
Should the macro be define in `src/csp_iflist.c` and `src/rtable/csp_rtable.c` or passed as an argument to gcc ?

2020-08-20 08:12 UTC, pi76r commented on src/drivers/can/can_riotos.c
> +#include "tja1042.h"
They are provided by RIOT directly, [here](https://github.com/RIOT-OS/RIOT/blob/master/sys/include/can/can.h).    
So --with-driver-can=riotos can only be compiled within riot os

2021-07-27 00:38 UTC, yashi commented on wscript
> +    gr.add_option('--with-driver-can', default=None, metavar='DRIVER', help='Enable can driver [linux, riotos]')
Please keep `meson.build` sync'ed.

2021-07-27 00:47 UTC, yashi commented
@millotp, please add some commit messages to each commit.
https://github.com/erlang/otp/wiki/writing-good-commit-messages

2021-09-27 15:39 UTC, johandc commented
Are you still interested in getting this in?

2021-10-30 11:35 UTC, closed without merging