[RFC] arch/zephyr: Add Zephyr RTOS support
libcsp/libcsp pull request #222
Opened 2021-08-01 10:24 UTC by yashi

This is a RFC PR.  DO NOT MERGE.

This commit add a RTOS called Zephyr[1].  This PR is not ready for merge.  It compiles and works on a real board with Zephyr with lo interface.  No hardware devices are included.

I'm creating this PR to ask everybody to check what I'm working on.
Some thing I'd like to highlight.

- Zephyr uses CMake based build system with modules support.  This PR make libcsp as a Zephyr module[2].  In order to do so, I've created `zephyr/` directory at top.  All source code is located under `arch/zephyr/`, though.  I'd like to ask it's OK or not.  I can move the files under the top directory but that'll clutter the top directory for sure.
- libcsp currently is using dynamic memory allocation.  Zephyr, instead, prefer static allocation over dynamic one.  I've made Queues and Semaphores as static allocation with hack.
- `csp_thread_crate()` is crated with C preprocessor macro in order to use static allocated stack memory location.  Because this is a macro, some limitation applies.
- samples under `zephyr/samples/` are, obviously, taken from `examples/`, to show we need to modify in order to run on another arch.  You can diff, i.e., `zephyr/samples/arch/main.c` against `examples/csp_arch.c`.  These files under `zephyr/samples/` will be removed before merge.
- files under `zephyr/tests/` are just for me.  They will be removed or refined before merge.

I'm sure I still miss some points I should make but without any further ado....  Please review :smiley: 

[1]: https://zephyrproject.org/
[2]: https://docs.zephyrproject.org/latest/guides/modules.html

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>

2021-08-01 14:05 UTC, johandc requested changes
This is generally accepted.

I have added a few suggestions for improvements, but there are more to the whole of CSP, instead of the zephyr stuff.

I haven't reviewed all the details, but am happy to host it inside a contrib/zephyr folder. I actually thought i would add that with example drivers for different chips too.

2021-08-01 14:05 UTC, johandc commented on include/csp/csp_types.h
> +#if ((CSP_BIG_ENDIAN && CSP_LITTLE_ENDIAN) || !(CSP_BIG_ENDIAN || CSP_LITTLE_ENDIAN))
Mental note to self.

I believe we only use the endianess for two things:
1) in csp_types.h we had the csp_packet_t structure which used bitfields for the header fields. With the introduction of  csp 2.0, all header fields have become native size, and there is a function (in csp_id.c) that takes care of the packing.

2) in csp_endian.c within arch/ - I don't know how many exotic compilers csp is built on. but i would rather rely on the now almost mandatory endian.h or machine/endian.h i havent checked which is the correct one. But this works on picolibc, linux and macosx. I don't know if zephyr has one?

2021-08-01 14:05 UTC, johandc commented on include/csp/arch/csp_thread.h
> +#define csp_thread_create(entry_point, name, stack_size, arg, prio, handle)	\
Static memory allocation is something i have long wanted in CSP.

My suggestion is to make a new API for static stuff providing the memory for the stack and the OS specific task handle.
So something in the lines of. https://www.freertos.org/Static_Vs_Dynamic_Memory_Allocation.html

```
static char stack[1024 * sizeof(int)]; //! We define stacksize in bytes
static csp_task_t handle;
csp_create_task_static(function, arg_ptr, stack, sizeof(stack), handle, sizeof(handle)); 
```

The same logic applies to semaphores and queues

2021-08-01 14:05 UTC, johandc commented on include/csp/arch/csp_thread.h
> +#if (!CSP_ZEPHYR)
I think it's okay for a platform to NOT define the dynamic memory API functions. As long as the static ones are there. CSP should be moved to static allocation internally. The only places where CSP is really using anything dynamic is already covered by memory pools, so the change should not be that difficult.

2021-08-01 14:05 UTC, johandc commented on zephyr/CMakeLists.txt
> +  set(CSP_DEBUG ${CONFIG_LIBCSP_DEBUG})
All of this would disappear with the introduction of #221

2021-08-01 14:05 UTC, johandc commented on zephyr/CMakeLists.txt
> +  set(CSP_BIG_ENDIAN ${CONFIG_BIG_ENDIAN})
All of this would disappear with the introduction of #223

2021-08-01 14:05 UTC, johandc commented on zephyr/CMakeLists.txt
> +  zephyr_library_named(libcsp)
Is there any way we could put this in either contrib/zephyr/CMakelists.txt or write the CMakelists.txt file generic, and move it to to the top folder to officially support CMake modules.
I can see theres a bit of zephyr specific stuff going on in here, and i'm not too familir with CMake. But isn't it bad to make a library use build macros defined outside the library itself?
could zephyr_library_named() and the other zephyr functions be reduces to native CMake syntax?

2021-08-01 14:05 UTC, johandc commented on zephyr/Kconfig
> +
All these files are acceptable, but i would like to put them under contrib/zephyr to make room for other project contributions without cluttering the top directory too much.

2021-09-16 08:57 UTC, yashi commented on zephyr/CMakeLists.txt
> +  zephyr_library_named(libcsp)
I think we can put it anywhere.
But unfortunately we can't use generic CMakeLists.txt, or at least we can't directly use the generic CMakeLists.txt from Zephyr's build system.  That is because CMake doesn't allow to have multiple [`project()`](https://cmake.org/cmake/help/latest/command/project.html).
Instead, we might be able to have a top level CMakeLists.txt dedicated for libcsp with `project()` and a shared CMakeLists.txt which will be included from both the top level CMakeLists.txt and Zephyr.  I'll test a bit to see whether we can or not.

2021-09-17 17:28 UTC, yashi commented on zephyr/CMakeLists.txt
> +  zephyr_library_named(libcsp)
I've investigated this a bit today.  The results is:
- It was easy to replace all `zephyr_*` variant in the CMakeLists.txt, but
- Zephyr module system [assume that there is `zephyr/module.yaml`](https://docs.zephyrproject.org/latest/guides/modules.html#module-repositories)
- With CMake, we usually descend from top level CMakeLists.txt to sub-directories.  [It's possible for a sub-directory to have `project()` and work with top level CMakeLists.txt](https://stackoverflow.com/questions/7980784), but
  1. It's not recommenced
  2. We can't mix bottom up (Zephyr) and top down (libcsp proper) because the top level CMakeLists.txt always descend into sub-directories.
  3. It's much more complicated.

So, is it OK to have `zephyr/` at the top level and make all files zephyr specific?

2021-09-17 17:31 UTC, yashi commented on zephyr/Kconfig
> +
I agree.  But Zephyr module system assume that `zephyr/` exist...

2021-09-19 08:15 UTC, johandc commented
@yashi 

Hmm, okay. I have two comments.

1) First of, maybe we can fix the zephyr module (assuming zephyr modules are github repos) with a symlink. So maybe after the initial clone, you could have a small script, that sets up a symlink between contrib/zephyr and /zephyr, and then we can add /zephyr to the .gitignore file, so it won't show up as a change. This avoids cluttering the base dir, but also helps the zephyr build system to grab csp as a module.

2) I think we should consider adding a CMakeLists.txt file to the base of libcsp for those who use CMake. Personally i use Meson, GomSpace uses waf, and others use CMake. So as long as there are hands to maintain the build file, i think we can support all three systems. I even think Meson has ways to interoperate with CMake. Would you be interested in adding a CMakeLists.txt file for libcsp? 

Note: The very latest version of CSP on spaceinventor/libcsp/2.0 contains static allocation only. And requires a few more defines compile time.

2021-09-19 12:28 UTC, yashi commented
I'll search a bit more how not to clutter the top dir just for Zephyr module.

I use CMake just because Zephyr build system is based on it.  I prefer Meson as well for my personal uses.  But I can add basic support for it.  Even, I might be able to find a good way to integrate libcsp with Zephyr in the course of a cmakanization.  Created #229.

My concern is: Do you really want to maintain three efferent build system?  We should at least have CI for each.

Just for the reference for other visitors, Meson does have [CMake module](https://mesonbuild.com/CMake-module.html#cmake-subprojects), but it's not tier 1.  See [Meson's policy on mixing multiple build systems in one build directory](https://mesonbuild.com/Mixing-build-systems.html)

2021-09-19 12:29 UTC, yashi commented
> Note: The very latest version of CSP on spaceinventor/libcsp/2.0 contains static allocation only. And requires a few more defines compile time.

I'll convert Zephyr port to the static version.  Thanks :smile:

2021-09-20 06:00 UTC, johandc commented
> 
> My concern is: Do you really want to maintain three efferent build system? We should at least have CI for each.
> 

Not sure how much work it would be. I have a feeling that CMake and Meson are pretty similar. But no. I would rather support only a single, but if you want CMake, you can go and do that :)

2021-09-26 15:00 UTC, johandc commented
Do you still need a contrib/zephyr folder now that there's CMake support native?

2021-09-26 15:26 UTC, yashi commented
I still need `zephyr/` directroy.  I've checked code and also asked a maintainer about it and it is hard coded in the source code.  So, I'm planning to make a fork of libcsp, or a branch on this repo if you are ok with it, to have just small portion of zephyr glue code.
There will be at least three files:
- `module.yml`: this is the one I can't move
- CMakeLists.txt: converts Zephyr config to libcsp configuration
- `Kconfig`: Zephyr configuration system
- some Zephyr specific samples if applicable

What do you think?

2021-09-26 15:45 UTC, yashi commented
I just pushed another RFC.  I know I haven't fixed things you have pointed out last.  This batch is to show you 
- how Zephyr port is now integrate with the CMake support, and
- static implementation of Zephyr, especially about staci initialization in `zephyr/samples/arch/main.c`.
```c
K_THREAD_STACK_DEFINE(stack, STACKSIZE);
```

I'll fix the things you pointed out in the next push.

2021-09-26 15:50 UTC, yashi commented on include/csp/arch/csp_thread.h
> -Copyright (C) 2012 AAUSAT3 Project (http://aausat3.space.aau.dk)
white space change.  will remmove.

2021-09-26 15:50 UTC, yashi commented on include/csp/arch/csp_thread.h
> -#define CSP_DEFINE_TASK(task_name) csp_thread_return_t __attribute__((stdcall)) task_name(void * param)
white space change.  will remmove.

2021-09-26 15:55 UTC, yashi reviewed
I just added some comments to myself.

2021-09-26 15:55 UTC, yashi commented on src/csp_service_handler.c
> +#endif
MISRA doesn't like alloca and Zephyr toolchain doesn't directly support it.  AFAIK, TI toolchain, [Code Composer Studio](https://www.ti.com/tool/CCSTUDIO), doesn't support it neither.

2021-09-26 15:55 UTC, yashi commented on zephyr/samples/arch/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.13.1)
will bump to the version 3.20.  (I think I used some feature from 3.20)

2021-09-26 15:58 UTC, yashi commented on src/csp_service_handler.c
> +#endif
I personally think that `alloca()` is same as large object on the stack, and love to use it.  But, ....

2021-09-26 16:31 UTC, johandc commented
What about the idea of having a pre build script setup a symlink from contrib/zephyr to /zephyr?

2021-09-27 06:31 UTC, yashi commented
**Short answer**:
No

**Long answer**:
The thing is that Zephyr's build is managed by a tool called [west](https://docs.zephyrproject.org/latest/guides/west/index.html) and it goes line this:
```shell
$ west init ~/myproject
$ cd ~/myproject
$ west update
$ west build --board qemu_cortex_m3 zephyr/samples/basic/blinky
$ west flash
```
where `west update` pulls all modules that the project depends on.  The first three steps are one time only.  That means that while in a development, You
1. modify your code
2. `west build` and test
3. Go back to 1

So, Yes, I can insert a new step (`ln -s ..../libcsp/contrib/zephyr ..../libcsp/zephyr`) after `west update` and before `west build`, Yes it's a persistent and one time only procedure for users, No it's not like a script-to-fix-them-all, because the path a module is placed in is arbitrary, depending on a project to a project. So,  I'd rather fork a repo for users so that they can follow what we have in [the Zephyr documents](https://docs.zephyrproject.org/latest/getting_started/index.html).

That said, if this is only me and my team, it's rather simple and take the symbolic link idea.  But we, Space Cubics, are planning to release the whole software as a SDK for cubesat.  That means that "users" will be someone who's new to the whole build process and I want it keep it simple and standard.

The unfortunate thing is that West doesn't have a hook which a module can use for whatever it needs, and, as said, the `/zephyr/module.yml` path is fixed right now. But we are discussing about enhancing module handing in Zephyr community.  Hope something comes up and fix this issue.  But, I'm sure it'll take a while.

So, I really appreciate your feedback and suggestion. But I'm thinking about placing `module.yml` in some other way if not allowed in the top directory.  (Don't take me wrong.  I understand that you don't want to clutter the top directory.  It's totally understandable.  I mean, many, if not all, modules have a dedicated repo forked from the upstreams. It's not just libcsp.)

ps. This is how I build and run libcsp `arch` sample
```shell
$ west build -t flash --board myboard modules/lib/libcsp/zephyr/sample/arch
```

2021-09-27 07:43 UTC, johandc commented
Okay, so here's the compromise:

1) You put the files into contrib/zephyr: This means their git location is where i want them. We also have a pull request for RIOT os, and i also want to make an extensive library of contributed network drivers, for CAN on different Chip's and so on. So the contrib directory is something i that i expect to grow.

2) We commit the symlink for /zephyr -> /crontrib/zephyr into the root of the main libcsp. This will of course clutter the root dir a bit, but let's not make it a bigger problem than it is at the moment. If we had 10 symlinks it would be annoying, but i think that a single is fine. I also would like to acknowledge your work and contribution. So i am happy to do that.

2021-09-27 08:40 UTC, yashi commented
Thank you for your kind words!

But, does it work under Windows / MacOS?

I know git handles symlinks OK on Linux but not sure others
https://github.com/git-for-windows/git/wiki/Symbolic-Links

I'm not currently planing to support Windows as a build env for our product, but both libcsp and Zephyr support them.

2021-09-27 15:00 UTC, johandc commented
Symlinks work on Mac.

Who cares about native windows build, even windows users are using Linux nowadays. There is no one left to maintain osx and windows support. So i think we should remove it with the 2.0 release.

I already removed windows build and Mac OS X from the CI.

2021-09-29 09:17 UTC, yashi commented on include/csp/csp_types.h
> +#if ((CSP_BIG_ENDIAN && CSP_LITTLE_ENDIAN) || !(CSP_BIG_ENDIAN || CSP_LITTLE_ENDIAN))
I have created #250 to address this.

2021-09-29 09:17 UTC, yashi commented on include/csp/arch/csp_thread.h
> +#define csp_thread_create(entry_point, name, stack_size, arg, prio, handle)	\
This one should be addressed by #247.

2021-09-29 09:19 UTC, yashi commented on zephyr/CMakeLists.txt
> +  set(CSP_DEBUG ${CONFIG_LIBCSP_DEBUG})
This issue has been discussed in #221.  And I'd like to address it after we merged Zephyr port.

2021-09-29 09:23 UTC, yashi commented on zephyr/CMakeLists.txt
> +  set(CSP_BIG_ENDIAN ${CONFIG_BIG_ENDIAN})
Unfortunately csp_rdp.c is still using it. https://github.com/libcsp/libcsp/blob/53d740adbdf6c269a33ab68c2f548b03590dad8f/src/transport/csp_rdp.c#L78-L94

2021-09-29 09:24 UTC, yashi commented on zephyr/CMakeLists.txt
> +  set(CSP_BIG_ENDIAN ${CONFIG_BIG_ENDIAN})
#250 has a commit to make sure that both defines are defined.

2021-09-29 09:27 UTC, yashi commented on zephyr/CMakeLists.txt
> +  zephyr_library_named(libcsp)
It turns out Zephyr module can use a plain CMake build, and it's already merged #231.

For the top level `zephyr/`, we decided to go with a symlink https://github.com/libcsp/libcsp/pull/222#issuecomment-927958792

2021-09-29 09:28 UTC, yashi commented on zephyr/Kconfig
> +
Will be in `contrib/zephyr/`.

2021-09-29 22:41 UTC, yashi commented on include/csp/arch/csp_thread.h
> +#if (!CSP_ZEPHYR)
I've removed dynamic memory API from Zephyr.

2021-09-29 22:44 UTC, yashi commented
OK, I think I've address everything we've talked about.  As mentioned in the commit log, rtable doesn't work right now due to an empty `sscanf()`, some warnings are generated, or even `<endian.h` is not availabe yet.  But it's just matter of time.  Hope it's OK to merge as is.  So that we can work on other parts.

2021-09-30 15:16 UTC, merged