[DNM] Add .editorconfig
libcsp/libcsp pull request #276
Opened 2021-10-30 16:03 UTC by yashi

Do not merge yet.

`.editorconfig` seems to be the way to enforce the coding style.  Major editors, including but not limited to Atom, Emacs, Eclipse, Sublime, VS Code, Vim, and many others, support it.

I only have *.c and *.h.  We should at least have

- [ ] meson.build
- [ ] wscript
- [ ] CMakeLists.txt
- [ ] *.py

Please let me know how you want them.

2021-10-30 16:16 UTC, johandc commented
I have been using this:
C_Cpp.clang_format_fallbackStyle: { BasedOnStyle: Google, IndentWidth: 4, ColumnLimit: 0}

2021-12-04 16:23 UTC, yashi commented
I'd like to reopen this because we haven't been able to use clang-format well.   We've discussed enabling style check for PRs but we haven't done it yet.  Until we have more sophisticated system on CI, editorconfig should do.

2021-12-05 08:43 UTC, johandc requested changes
Tabwidth should be 4

2021-12-05 15:45 UTC, yashi commented
Do you want to use tab or space for `meson.build`, and width?

2021-12-05 16:14 UTC, johandc commented
I think tabs and 4.

2021-12-05 16:14 UTC, merged