src/bindings/python: Fix python binding for sfp_recv
libcsp/libcsp pull request #290
Opened 2021-11-06 08:40 UTC by IlievIliya92

src/bindings/python: Fix python binding for sfp_recv
       
 The returned encapsulated object is returned as raw bytes using:
 the data from 'dataout' with length 'return_datasize'

2021-11-06 23:10 UTC, yashi requested changes

2021-11-06 23:10 UTC, yashi commented on src/bindings/python/pycsp.c
> +    return Py_BuildValue("y#", dataout, return_datasize);
You are leaking `dataout` here.  `csp_sfp_recv()`, or `csp_sfp_recv_fp()` to be exact,  `malloc()`s a memory region and copy received packets in it, then returns as `dataout`.  `Py_BuildValue()` will `memcpy()` frp, the given `dataout` to the newly created bytes object.

> In order to deallocate the memory for the "dataout" pointer it is required to use "csp_free".

As said above, `dataout` is `malloc()`ed.  Thus, this is false.  You can just `free()` it.  But, in order to avoid the extra `memcpy()`, why not keep using `PyCapsule_New()` with `free()`?  Doesn't it work?  I don't have sfp python code so I can't test.

Also, it used to return a Capsule object but now return a bytes object.  But this should be OK, I assume.

2021-11-07 09:48 UTC, yashi commented on src/bindings/python/pycsp.c
> +    return Py_BuildValue("y#", dataout, return_datasize);
BTW, we are removing dynamic allocation from libcsp.  it'd be nice if we can remove malloc() from sfp.

2021-11-08 17:52 UTC, johandc commented
Hello.

I commented out SFP because I wanted a malloc free (no pun intended) CSP implementation. Do you really use SFP? It's quite inefficient and error prone due to the lack of retransmission.

CSP now supports packets size of 2kB. So I suggest increasing MTU size og switching up to RDP for larger data transfers.

2021-11-10 04:47 UTC, IlievIliya92 commented
Hi, 

Sounds, great! Will use a larger MTU size instead. Thank you for the information!

2021-11-10 04:47 UTC, closed without merging