Yaml
libcsp/libcsp pull request #301
Opened 2021-11-21 17:00 UTC by johandc

Added yaml configuration format

For our Posix/C based tools (satctl), we have a plethora of command line options to try and configure various interfaces. It doesn't get better now that each interface should have its own address and netmask. So in order to ease configuration i have added a small yaml file.

I wanted to add this to CSP because i belive other tools may benefit from this too.

It depends on libyaml, and automatically byilds the functions if it's available on the system. It also depends on malloc.

oh and btw. the implementation is lossy, i haven't bothered cleaning up string's and such, because it's an init time tool only and mostly running on PC. I should probably add a note to the source file about this, before someone comes yelling at me :)

2021-11-21 21:03 UTC, yashi requested changes
Is there public repo for satctl?  It'd help if I can test it when I review.

I'd make a simple state machine for `iflist_yaml_init()`.  The current implementation takes any scalar event.  The state machine is very simple:

1. document start
2. sequence
3. mapping
4. scalar (as key)
5. another scalar (as value) (go back to 4)
6. many end sections

But we can fix it when we need it.

Everything else is nitpicks.

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    char *name;
perhaps * at the middle?
I guess we need to `clang-format` this file?

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    assert(yaml_parser_parse(&parser, &event));
Please move the functions out of `assert()`.  It should be tested with and without assert.

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +}
no newline at the end.

2021-11-21 21:03 UTC, yashi commented on meson.build
> +yaml_dep = dependency('yaml-0.1', required : false)
I'd write
```meson
yaml_dep = dependency('yaml-0.1', required : false)
conf.set('CSP_HAVE_LIBYAML', yaml_dep.found())
csp_deps += yaml_dep
```
And move `csp_sources += files(['src/yaml/iflist_yaml.c'])` down to `src/yaml/`.  I wanted to other `csp_sources` to where the source files are, as well.

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +	csp_rtable_set(atoi(data.addr), csp_id_get_host_bits(), &csp_if_lo, CSP_NO_VIA_ADDRESS);
Indent.

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +} data;
I wouldn't use a global variable.  pass it to the functions accessing it.  We can create it as a local variable in `iflist_yaml_init()`

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    /* ZMQ */
`#if (CSP_HAVE_LIBZMQ)`

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    /* CAN */
`#if (CSP_HAVE_LIBSOCKETCAN)`

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    /* CAN */
Or we can perhaps move this block to libsocketcan driver.  Make it so that in the header file

```c
#if (CSP_HAVE_LIBSOCKETCAN)
extern int csp_can_socketcan_set_if(...);  // or what ever the name is
#else
static inline int csp_can_socketcan_set_if() {}  // make it noop when disabled.
#endif
```

If we have these interfaces installed. this part of the file will be

```c
if (strcmp(data.driver, "zmq") == 0) {
    csp_zmphub_set_if(...);
} else if (strcmp(data.driver, "can") == 0) {
    csp_can_socketcan_set_if(...);
} else {
    log_error("Unsupported interface");
}
```

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +                printf("Extected value\n");
typo?

2021-11-21 21:03 UTC, yashi commented on src/yaml/iflist_yaml.c
> +            if (event.type != YAML_SCALAR_EVENT) {
I couldn't reproduce this case.  Do you have a data file for this?

2021-11-21 22:28 UTC, johandc commented on src/yaml/iflist_yaml.c
> +    assert(yaml_parser_parse(&parser, &event));
Right, that came directly from an online example 😆

2021-11-21 22:29 UTC, johandc commented on meson.build
> +yaml_dep = dependency('yaml-0.1', required : false)
Okay, i agree

2021-11-21 22:30 UTC, johandc commented on src/yaml/iflist_yaml.c
> +} data;
Good Idea

2021-11-21 22:31 UTC, johandc commented on src/yaml/iflist_yaml.c
> +    /* ZMQ */
Oh, yes.

2021-11-21 22:35 UTC, johandc commented on src/yaml/iflist_yaml.c
> +    /* CAN */
I think it would be best to produce a warning, when trying to initialise an unsupported interface. I actually think it's nice of the header would simply take care of that, instead of clobbering the code with checks.

2021-11-21 22:36 UTC, johandc commented on src/yaml/iflist_yaml.c
> +                printf("Extected value\n");
Yes

2021-11-21 22:49 UTC, johandc commented
Thanks for a very good review. I have been focusing on making stuff work today. Your help, in getting the details right is much appreciated.

> Is there public repo for satctl? It'd help if I can test it when I review.

Yes. It's open source and on: 
github.com/spaceinventor/satctl

> 
> I'd make a simple state machine for `iflist_yaml_init()`. The current implementation takes any scalar event. 

Haha, i actually threw away the state machine from the reference implementation and reduced number of line from 300 to 100 this way. This is much easier for the eyes, and works just as well when the schema is predefined like here. If it sees anything not as it expects it just quits. 

So in my opinion, unless we need to parse arbitrary trees into objects, tjen a state machine isn't needed.

What do you think about the idea of the yaml file in general? I think the network configuration just got more difficult, in that we have more parameters, and yet again it was a mess with all the old runtime flags.

I actually want to add routing table, and other CSP init parameters there too. And have a flag to select which config file to start satctl with.

As for the embedded use, none of this yaml nonsense hokus pokus is required. Since the amount of network interfaces is typically fixed. And parameters can be used to initialise them in static ram.

2021-11-22 02:25 UTC, yashi commented
> What do you think about the idea of the yaml file in general?

To tell the truth, I don't know.  I haven't setup a complex CSP network yet.  But given that CSP 2.0 supports 16k addresses, I'm sure we need some mechanism to setup everything right.  I don't know how you guys manage the network settings for many cubesats with many components.  I'd love to learn it from you.

My current idea is to have a single file to describe the whole network of cubesat including GS (emulated by PC).

Say you have five components in a cubesat, two of them are purchased from other companies, three are your own building from source.  How would you make sure that network configuration on all components are right?  Should we extend this yaml capability to setup everything?  Or is it totally different issue?

I think we can generate binary blob from yaml describing routing tables and link it against the final image for embedded systems.  We can also extend `satctl` to update network setting of nodes, if it doesn't have the capability yet.  (or is it handle by [spaceboot](https://github.com/spaceinventor/spaceboot)?) But I'm not sure the single file for cubesat network is a good way to go.

If this yaml conf is only for PC, we can go wild :wink: 

Oh, it might be a good idea to pass a file name from a tool, such as `satctl`, to the API.

> Yes. It's open source and on: [github.com/spaceinventor/satctl](https://github.com/spaceinventor/satctl)

Thanks :+1:

2021-11-22 09:51 UTC, johandc commented
> To tell the truth, I don't know. I haven't setup a complex CSP network yet. But given that CSP 2.0 supports 16k addresses, I'm sure we need some mechanism to setup everything right. I don't know how you guys manage the network settings for many cubesats with many components. I'd love to learn it from you.

We go from the top down.
0) Select CSP version. If you have legacy products and are forced go with v1. otherwise select v2.

1.1) How many satellites will be in the constellation = min number of subnets
1.2) How many nodes will be on each satellite = min number of host addresses.
1.3) Select a subnet mask that falls in between 1.1 and 1.2
note: We typically use 8 as netmask, allowing for 256 subnets, with 64 nodes per satellite.

2.1) For each satellite-bus assign a subnet
2.2) For each point-to-point linik assign a subnet (these can have much higher netmask 12 for example)
2.3) For RF links, decide wether they operate in a BUS (all with same RX/TX freq. and conf) or point-to-point, each link individual. Assign subnet of the size that matches to a bus or point to point.
2.4) For encrypted links assign tunnel endpoints (csp_if_tun) (more advanced than this)
2.5) Make a topology diagram showing only the subnets and how they are inter-connected, possibly the gateway and their addresses. Take special notice of cases where redundant gateways exist. For example having a satellite with multiple receivers, or a ground station network with multiple stations.

3.1) Within each subnet assign individual node addresses. These are static for the entire mission duration and can be input into the nodes by config parameters. The gorund segment can be more loose with its client addressing, since mission control clients can typically spawn at will.

 
> My current idea is to have a single file to describe the whole network of cubesat including GS (emulated by PC).

That would be awesomme if combined with a tool to create graphs.
https://graph-tool.skewed.de/static/doc/draw.html

 
> Say you have five components in a cubesat, two of them are purchased from other companies, three are your own building from source. How would you make sure that network configuration on all components are right? 

I would make it a requirement that:
1) The systems support either CSP 1 or 2.
2) The systems come with a means of changing the node-id-
3) If 2 is not possible. They must be ordered with the correct address. So make very sure it's the final decision before ordering.

Should we extend this yaml capability to setup everything? Or is it totally different issue?

I don't think the topology description belongs to the satellite, or configuration format. Each node should have their separate config (on PC via YAML, on satellite via fixed parameters)

 
> I think we can generate binary blob from yaml describing routing tables and link it against the final image for embedded systems. 

CSP already supports reconfigurable routing table through the `csp_rtable` parameter. It's a text string which are parsed by CSP in the CSV format "node/mask interface, ...."

> We can also extend `satctl` to update network setting of nodes, if it doesn't have the capability yet. 

`satctl` can modify parameters on nodes, and therefore also modify the CSP configuration. Not that it's dangerous to mess with while in orbit. Therefore a special recovery procedure is proposed to become part of CSP. (i haven't written the spec yet, but it relies on layer-2 broadcast, which i'm getting to)

> (or is it handle by [spaceboot](https://github.com/spaceinventor/spaceboot)?) 

No, spaceboot is just for image transfer.

> If this yaml conf is only for PC, we can go wild wink

If the libyaml wasnt a big monster, we could use it for the satellite. But i think it's a waste of energy, since most subsystems are pretty static.
 
> Oh, it might be a good idea to pass a file name from a tool, such as `satctl`, to the API.

Yes.

2021-11-22 13:20 UTC, benner commented
> 1.1) How many satellites will be in the constellation = min number of subnets
> 1.2) How many nodes will be on each satellite = min number of host addresses.
> 1.3) Select a subnet mask that falls in between 1.1 and 1.2
> note: We typically use 8 as netmask, allowing for 256 subnets, with 64 nodes per satellite.
> 
> 2.1) For each satellite-bus assign a subnet
> 2.2) For each point-to-point linik assign a subnet (these can have much higher netmask 12 for example)
> 2.3) For RF links, decide wether they operate in a BUS (all with same RX/TX freq. and conf) or point-to-point, each link individual. Assign subnet of the size that matches to a bus or point to point.
> 2.4) For encrypted links assign tunnel endpoints (csp_if_tun) (more advanced than this)
> 2.5) Make a topology diagram showing only the subnets and how they are inter-connected, possibly the gateway and their addresses. Take special notice of cases where redundant gateways exist. For example having a satellite with multiple receivers, or a ground station network with multiple stations.
> 
> 3.1) Within each subnet assign individual node addresses. These are static for the entire mission duration and can be input into the nodes by config parameters. The gorund segment can be more loose with its client addressing, since mission control clients can typically spawn at will.

Awesome addressing/network planing strategy.  This can be placed outside PR/issue and put into docs or other findable place.

2021-11-22 21:31 UTC, johandc commented on src/yaml/iflist_yaml.c
> +            if (event.type != YAML_SCALAR_EVENT) {
Hmm, yes it seems that if no value is given, libyaml will automatically create a scalar value of 0. Which means it's impossible to create a parse error. So i'm removing the check for cleaner code.

2021-11-22 21:42 UTC, johandc commented
All suggestions is implemented, but i'm waiting with the merge because this was based on the broadcast branch. And i'm expecting the broadcast branch to be merged soon.

2021-11-23 03:44 UTC, yashi approved these changes
Looks good to me. Thanks.

I've added a few comments for me asking how you want the style to be.  Nothing blocking.

BTW, does your editor support squashing this commit into the commit "Added yaml configuration format" (31d5223cfb1517519) ?  Or do you like to have a separate commit for review response?

2021-11-23 03:44 UTC, yashi commented on include/csp/csp_iflist.h
> +void iflist_yaml_init(char * filename);
ending newline is missing.  I searched setting for clang-format but couldn't find it.  Do you know whether it supports it or not?

2021-11-23 03:44 UTC, yashi commented on meson.build
> -endif
We should note about this in the commit log that this has been removed because we already have it under interface.

2021-11-23 03:44 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    if (0) {
I'd add
```c
    /* We must have this empty if for the last else block */
```

2021-11-23 03:44 UTC, yashi commented on src/yaml/iflist_yaml.c
> +		printf("Adding ZMQ interface: %s node %s\n", data->name, data->addr);
how about
```c
	/* We must have this empty if for the last else block */
	if (0) {
	}
#if (CSP_HAVE_LIBZMQ)
	/* ZMQ */
	else if (strcmp(data->driver, "zmq") == 0) {
	    :
	}
#endif
#if (CSP_HAVE_LIBSOCKETCAN)
	/* CAN */
	else if (strcmp(data->driver, "can") == 0) {
	    :
	}
#endif
	/* Unsupported interface */
	else {
	    :
	}
````
This is more consistent.

2021-11-23 03:44 UTC, yashi commented on src/yaml/iflist_yaml.h
> +void iflist_yaml_init(char * filename);
missing end-of-file newline.

2021-11-23 03:44 UTC, yashi commented on src/yaml/iflist_yaml.c
> +    /* Unsupported interface */
I think you missed running clang-format again after you edited?  It has spaces instead of a tab.

2021-11-23 06:34 UTC, johandc commented
I normally don't do squashing, it's mainly used by larger projects to keep each pull request to single commit messages in the log. Which is nicer or course. But on a day to day basis on a project I mainly maintain myself, o don't care so much about the commit log. I even do regular merge commits too. Faster, gets the job done. Next issue.

I would like to get my discipline better some day, but I'm lacking the personal incentive to spend time learning the squash. Furthermore I feel like it rewrites history a little too much for a little project like this.

Your other comments are duly noted, at some point I feel like a script to apply clang format to the entire tree will be useful.

2021-11-24 15:04 UTC, johandc commented
@yashi  @jledet  
I apologise, that i mentioned 'satctl' as an open source program. We didn't have the right to that name so it has been changed to https://github.com/spaceinventor/spacepromt instead.
Best, Johan.

2021-11-24 21:44 UTC, merged