Simplify assert and stdout from library
libcsp/libcsp pull request #304
Opened 2021-11-27 20:29 UTC by johandc

Fixes #221 

The CSP core never emits calls to printf, instead it uses error counters for typical errors. And a global errno with codes for rare errors. The packet and protocol logs have been converted into flags, which enable the printf to stdout of these two. lock debugging have been wiped, i didn't feel it was necessary or used ever.

The new error counters will be able to catch many more overflow, and underruns than the old string based error log system. While the errno should simply always be 0. If it's not something is not setup correctly or there is a bug in the code.

The can interface gets it's own errno, because an error on the CAN bus isn't necessarily a bug within CSP. But rather on the bus.

The way to access these variables is to include <csp/csp_debug.h> from your application.

2021-11-30 09:32 UTC, bfol requested changes
From Gomspace point of view, we have 2 main concerns. 
1) The pollution of stdout with printf. We prefer to have printouts done via a macro, so that we can override these and print to a different stream if wanted. 
2) Loosing the ability to override the printouts from CSP (CSP_USE_EXTERNAL_DEBUG)

Otherwise it looks good

2021-11-30 17:43 UTC, johandc commented
> From Gomspace point of view, we have 2 main concerns.
> 
> 1. The pollution of stdout with printf. We prefer to have printouts done via a macro, so that we can override these and print to a different stream if wanted.
> 2. Loosing the ability to override the printouts from CSP (CSP_USE_EXTERNAL_DEBUG)

@bfol 
Okay to me it sounds a little like the same thing. But I get your point. This is why there is no printf or stdout of any kind left inside CSP.

Regarding those few cases that remain, the old macro system was a little cumbersome and convoluted. How about we make a macro like this:

```c
#ifndef CSP_PRINTF
#define CSP_PRINTF printf
#endif
```

And the the build script could replace `CSP_PRINTF` with any function from your log system as long as it keeps the format, vaargs arguments.

2021-12-01 06:12 UTC, johandc commented
Actually it would be even cooler if we could get error codes for the last interfaces too, so there would be no need for stdout at all.

Regarding the very useful packet printout. It think we should make that as a user hook on incoming and outgoing. In fact that could even be used for stuff other than just the printout.

And the RDP debugging is something that is only rarely used, but I want to leave it in place with a toggle, and perhaps a compilation option to disable it, to save the large amount of strings inside.

2021-12-01 06:17 UTC, johandc commented
Another thing is that I might want to do is add weak linked implementations of many of the hooks. How do you like that idea?

2021-12-01 08:23 UTC, bfol commented
Converting the remaining printf to error codes and weak linked hooks would be the best option in my view. Especially a hook on packet input / output would be really usefull

2021-12-01 11:53 UTC, johandc commented
Okay, great I will do that.

2021-12-01 16:50 UTC, yashi commented
### Global error number vs return values

I don't see the point of having a global variable, `csp_dbg_errno`, instead of just a simple return value.  It's racy under multi-threads env we are all in.

Despite the name, it's not even a debugging facility.  It's actually the obligation of application authors to check how functions behaved.

This `csp_dbg_errno` thing is a big NAK from me.

This is related #234

### Subsystem error counter

I like the idea.  I'm not sure we should have fixed `csp_dbg_` prefix though.

If it's not atomic, we should use mutex to protect it. Yes, with ARM instruction, integer increment is atomic if and only if one thread is writing.  But, it should be good practice and relates to the next point.

We should allow variable sizes for the counter.  Some mission might want to use 64 bits for the counter.  If 64 bits are chosen, we need a lock or the counter must be atomic.

I don't know it's a good idea to make the variables global.  If the value is read-only for applications, it might be better to have a read accessor for them.

### Debugging printf

As have already mentioned, we, Space Cubics, wanted to replace them with our own custom functions.  But with subsystem error counters installed, and good error indication from function return values, we might not need it at all.  I haven't checked it fully just yet.

stdio is huge and we don't want it in our spacecraft.  But I'm sure it's nice to have while debugging.

### Other comments

I've started review this PR but honestly it's quite hard to see what's going on.

As noted by you, the PR consists 3 different issues with 9 commits, without telling which one does which.  I'll just list them here for me and any one visiting this PR in future.  No other intention is associated with it.

- **Remove assert from csp**
  - This should be the one for #221 
  
- **merge master**
  - It says "merge master" but it's not every merge commit.
  - This has the new debug APIs in it.  New symbols, `csp_dbg_init_errno`, `csp_dbg_inval_reply` and many other `csp_dbg_*`; new defines `CSP_DBG_*` in `csp_debug.h`
  - This commit replaces `csp_log_*()` with `printf()` by introducing (temporarily?) `stdio.h`.
  - So this is definitely for #221, but two big parts listed above. (nice to split)
  - But I might have missed something from "merge" part.
    
- **Cleanup in debug header**
  - This moves newly introduced symbols in `csp_debug.c`, and
  - Remove unused csp_debug related macros.
  - Rename a few newly introduced symbols.
  - This should be part of the former part of the previous commit (squashed to one after the split)
    
- **Fix examples and add color to packet and rdp print**
  - This actually has four parts:

  1. fixing code under `examples/` by removing old symbols
  2. introducing terminal colors in macros in `csp_debug.h`
  3. `csp_print_packet()` fix for newline handling
  4. removing redundant debug part from the build systems

- **do not use csp_conn objects for listener sockets**
  - `csp_port.c` indeed introduce two new callbacks, `csp_port_get_callback()` and `csp_bind_callback()`.
  - And, `csp_listen()` now call `csp_queue_create_static()`
  - So this is #242
  - But, many other parts are debug macro renames, which hide the important changes in `csp_port.c`
  - somehow csp_types.h now includes `csp_queue.h` and `csp_semaphore.h`, along with `struct csp_socket_s` from `csp.h`.
    
- **Fix build on freertos" and "Fix example and cmake build**
  - fix regression caused by other commits
  
- **Global RDP retransmission queue**
  - #241
  
- **Updated changelog**
  - just as it says.

2021-12-01 20:28 UTC, johandc commented
First of all, thank a lot for a very good review. I have been looking forwards to this one.

First of all, once again I can only apologise for the messy commits. The thing is that I couldn't implement these things without eachother. And the way GitHub handles merges, it automatically takes every into one pull request.

Also the merge commit was a mistake, it should have been a rebase, but after fixing a conflict it turned into a merge. 

Your dissertation of the individual changes is perfect. So no comments on that. I will address each of the major points in separate replies below

2021-12-01 20:39 UTC, johandc commented
> Global error number vs return values

Okay, i know that it's racy, but it may be the best solution and here is why.

1. It does not replace any return values. And the user is never required to check the error number for anything. Period.
2. It is only used for very rare error events that previously had a printf. For example if a null pointer is passed to csp_close or stuff like that. Stuff that shouldn't ever happen.
3. All the print outs that actually can happen, under normal operation like buffer underrun, and connection flooded are now in counters. A counter is much better than a printf.
4. Removing the printfs saves code size
5. Including the very rare stuff as special return values, just leaves the problem to the user to handle. And this adds to the code size and leads to more confusing API.
6. For many functions all that matters is wether it was successful or not. And like with the new csp_send() it is fire and forget. So CSP handles any errors internally.
7. The value of the CSP errno should always be zero. All the errors going in here is a sign of a malfunctioning system. So controlling that it's zero is only required if any network issues appear.

I think as a solution to the global errno, I will add a hook together with a weak implementation, so the user can catch the error codes themselves and do what they want with it. So CSP will default to a global.

2021-12-01 21:09 UTC, johandc commented
> Subsystem error counters

Each interface already has error counters, so I just expanded it to cover other parts of the stack.

Again it's not something that requires to be checked by any means. But if there is an issue, and you are loosing packets. Reading the debugging counters can point to the cause.

Suggestions for better names?

I want the memory address to be accessible from the outside. In order to map the variables to our parameter system. For remote read access.

Also I don't want any runtime setup, the symbols should be available to the linker. Because the mapping happens compile time.

Adding acessor functions just adds more code to do runtime what can be done compile time. 

The csp_conf struct is also a global, on order to reduce namespace clutter i could put the counters inside a struct.

I think this is the simplest solution to just have them being accessible as a global. And they are prefixed with csp_ so it's not like it should conflict with other variables.

Regarding atomic access, we should let the compiler handle that and use <stdatomic.h>. We don't want to introduce locks inside of a debugging function that can happen inside an isr. So maybe we just use 'atomic_uint_8'

The compiler actually reduces this to a single atomic instruction on most platforms. Which is pretty nice.

I chose uint8 for the space savings, and because it doesn't matter if an error counter wraps around. It's not the absolute number that's interesting. It's the fact that there was a change between two events for example. So usually while debugging you read out the value first, then perform an action and read out again. So no need for uint64.

2021-12-01 21:16 UTC, johandc commented
> Debugging printf

We have only two places where CSP would make calls to printfs left. And that is the packet printout, and the protocol debugging, which i still actively use when working with RDP.

I think I just agreed with bfol, to make the packet in/out event into a hook, with a weak implementation defaulting to printf when that flag is set.

And the protocol debug i think will be changed into a compile time enable, because it's actually only meant for the developer. 

We do have some printfs remaining on Linux only stuff like zmq and socketcan. But let's try to remove those too.

Finally stdio.h isn't that bad, if you use picolibc. It's tiny, low stack usage and does not use malloc().

2021-12-01 21:25 UTC, johandc commented
Final comment. Globals aren't always bad. Especially on Embedded. Because it can be a tedious task to pass down and cary around a CSP instance pointer through each and every function call. Especially because CSP is not designed to be multiple instances. It will always be the same pointer anyways.

And making the variables static means we would need a function call to get a pointer, which produces larger code and runs way slower. And if that function always returns the same pointer it might as well be available as a symbol.

2021-12-02 05:43 UTC, yashi commented
> Globals aren't always bad.

No, of course not.  Passing a parameter to a deep function chain pollute CPU registers and slow things down.  So if you have to run a tight loop with a value under a deep calls, global variables can save you.  But, we don't have a deep call chain in CSP.  We don't want a deep call chain because of limited stack size.

> Adding acessor functions just adds more code to do runtime what can be done compile time.

That's true! If the accessor code for each rarely used variables adds up, that's bad for restricted devicees.  And this is a good and a valid reason to use global variables.  So I agree on using global variables.  ​A bit more on below.

But,

> Because it can be a tedious task to pass down and cary around a CSP instance pointer through each and every function call.

I don't think this is a good reason.  tedious to write?  embedded software _is_ tedious to write because all nominal passes are about 20 % of the total system.  80 % is error checking and abdominal code pass we don't want to happen in the field.  OK you didn't mean this. :stuck_out_tongue_winking_eye:  But, we write reusable code once because we don't want to repeat tedious work again.  But someone must write that code for this messy unpredictable real-world so that all others can lazily use the code.  (Being a lazy is a good thing for a programmer, right :wink:)

> CSP is not designed to be multiple instances

If so, I can understand and I think it's a valid reason to have one single global csp instance and all function referencing to it.  That will reduce register pollution as well.

> making the variables static means we would need a function call to get a pointer

This is a good point to use global variables in embedded system until LTO is widely used!  Both GCC and Clang already supports `-flto`.  But Zephyr doesn't not support it yet.  How about FreeRTOS?

> i could put the counters inside a struct.

A good pre defined prefix should be enough, IMHO.  Or is there any merit of using struct that I don't see?

2021-12-02 06:02 UTC, johandc commented
> But someone must write that code for this messy unpredictable real-world so that all others can lazily use the code. (Being a lazy is a good thing for a programmer, right 😉)

I cannot agree more on this. Best example is csp_send. CSP should be so easy to use, that it is not even required to check the return value of the send function, in order to avoid a buffer leak.

(If we want the old behaviour back, it will be a different function, which allows for retrying with the same buffer.)

The debug variables are really meant as lazy mans measure, to get the cause, if something is not looking right. The normal use cases, should not be polluted with extremely rare return values, that the user won't check for anyways.

In general it was a mistake to carry along FreeRTOS convention of returning pdTRUE which is a define set to 1. I believe it's nicer to use the zero good everything else bad approach. But that is another issue #209

2021-12-04 15:53 UTC, yashi requested changes

2021-12-04 15:53 UTC, yashi commented on src/csp_debug.c
> +}
Make this an inline function in csp_debug.h so that we don't even have to branch to this empty function if want to disable calling `csp_print()` when `!CSP_DEBUG`.  Compilers will optimized this out.

Also, you don't need weak here.

2021-12-05 08:40 UTC, johandc commented on src/csp_debug.c
> +}
It cannot be a preprocessor macro, if the function should be weak linked and overridden at link time. By a user supplied implementation.

I originally suggested at simple define, but I'm not sure it was enough to satisfy the need of gomspace. As the old system allowed to override.

2021-12-05 15:23 UTC, yashi commented on src/csp_debug.c
> +}
I said _inline function_, not a preprocessor macro.

Do you want user to override `csp_print()` when `!CSP_DEBUG`? And do you want to supply non-debug version of `csp_print()`, which is just empty function?  If that's your intention, can we do:

```c
#if (CSP_DEBUG)
#include <stdio.h>
#endif

__attribute__((weak)) void csp_print(const char * fmt, ...) {
#if (CSP_DEBUG)
    va_list args;
    va_start(args, fmt);
    vfprintf(stdout, fmt, args);
    va_end(args);
#else
    return;
#endif
}
```
This tells to reader that our intentions are
- We always provide weak version of `csp_print()`.
- When `CSP_DEBUG`, we provides `vfrpintf()` as the default, which to be overridden.
- When `!CSP_DEBUG`. we provide an empty function as the default, which to be overridden.

If you don't want user to override `csp_print()` when `!CSP_DEBUG`, you can do the following in the _header file_.  This i what I suggested in the previous comment.

**in the .c source file**
```c
#if (CSP_DEBUG)
#include <stdio.h>

__attribute__((weak)) void csp_print(const char * fmt, ...) {
    va_list args;
    va_start(args, fmt);
    vfprintf(stdout, fmt, args);
    va_end(args);
}
#endif
```
**in the header file**
```c
#if (CSP_DEBUG)
void csp_print(const char * fmt, ...);
#else
inline void csp_print(const char * fmt, ...) {}
#endif
```

This can tell compiler to optimize out the branch instruction to the empty funciton, which is not possible without LTO because the function body is in the other compile uint.

2021-12-05 16:54 UTC, johandc commented on src/csp_debug.c
> +}
Oh, wish i saw this before. 

I ended up with something very similar, using the preprocessor to remove the printout alltogether.

2021-12-05 17:18 UTC, johandc commented on src/csp_debug.c
> +}
I ended up renaming CSP_DEBUG to CSP_HAVE_STDIO (inline with some of the other header HAVE_LIB_SOCKETCAN and HAVE_LIB_ZMQ)

This means we can rather easily remove stuff that depends on stdio, such as snprintf, and scanf.

I realize that there could be cases where the user does NOT want to include STDIO in CSP, but the DO want to override the function. But i'm also in doubt if adding an extra option such as CSP_ENABLE_PRINT is really necessary.

2021-12-05 23:03 UTC, johandc commented
Final call,

I took care of a bunch of stuff and wiped the last few issues i had remaining. It's a little all or nothing with this commit. If there's something you don't like we can still change it on develop after the merge.

2021-12-06 13:02 UTC, merged

2021-12-06 13:06 UTC, bfol commented on include/csp/csp_hooks.h
> +#include <csp/csp_types.h>
Missing #pragma once

2021-12-06 13:06 UTC, bfol commented on src/csp_service_handler.c
> -		case CSP_PS: {
We still use this functionality. If its remove due to removed arch support, it would be find to add a HOOK that can be implemented externally

2021-12-06 14:35 UTC, johandc commented on src/csp_service_handler.c
> -		case CSP_PS: {
I think it should be moved outside CSP. Because it has nothing to do with the network stack. I also wanted to move memfree, but that was to tiny I left it.

What is your opinion, should task list be part of CSP?

2021-12-06 14:35 UTC, johandc commented on include/csp/csp_hooks.h
> +#include <csp/csp_types.h>
Thanks

2021-12-06 16:12 UTC, johandc commented on src/csp_service_handler.c
> -		case CSP_PS: {
@bfol 

We just moved the tasklisk to a parameter called os_print_dbg, when that is set to 1, FreeRTOS prints it's debug information including the task list in ASCII to our stdout where we collect it from.

I know you have an external log system, so it should be easy for GS to make such a parameter.

POSIX systems has other ways of debugging tasks, so I don't think it really belongs in CSP

2021-12-07 06:42 UTC, bfol commented on src/csp_service_handler.c
> -		case CSP_PS: {
removing CPS_PS completely is not backwards compatible. This is my main concern. As I wrote in my original comment, I am perfectly fine with changing the implementation to a hook instead, so the user can choose to implement the functionality the way he want's

2021-12-07 16:58 UTC, johandc commented on src/csp_service_handler.c
> -		case CSP_PS: {
I have created a new thread on this and other things i would like to deprecate.