src/csp_io.h: send direct pass idout struct by reference
libcsp/libcsp pull request #359
Opened 2022-04-15 13:45 UTC by fjmolinas

This changes the `send_direct` api to pass the structure pointer to `id` by reference instead of by value. I'm not sure if this was done with the intention of having no side effects. In my case I actually want to know what was set as the destination address for messages, passing it by reference addresses this issue.

2022-04-15 21:38 UTC, johandc requested changes
I like it.

The reason for this is legacy from when a csp_id_t was a uint32, in a packed bitfield. So this improvement will avoid a lot of stack usage for this call.

2022-04-15 21:38 UTC, johandc commented on src/csp_io.c
> +	printf("set outgoing address %"PRIx16":%d\n", packet->id.src, packet->id.sport);
Stray printf should be cleaned before merge

2022-04-19 14:00 UTC, fjmolinas commented on src/csp_io.c
> +	printf("set outgoing address %"PRIx16":%d\n", packet->id.src, packet->id.sport);
ups

2022-04-19 14:01 UTC, fjmolinas commented on src/csp_io.c
> +	printf("set outgoing address %"PRIx16":%d\n", packet->id.src, packet->id.sport);
addressed and squashed

2022-04-19 14:13 UTC, fjmolinas commented
Rebased to fix conflicts

2022-04-19 21:57 UTC, johandc approved these changes

2022-04-19 21:57 UTC, merged

2022-04-20 07:08 UTC, fjmolinas commented
Thanks for the review and merging!