src/csp_rtable_stdio: set _DEFAULT_SOURCE to 1
libcsp/libcsp pull request #362
Opened 2022-04-19 14:45 UTC by fjmolinas

This was required for me to build with newlib-nano:

```
/home/francisco/workspace/RIOT/build/pkg/libcsp/src/csp_rtable_stdio.c:19:25: error: implicit declaration of function 'strnlen'; did you mean 'strlen'? [-Werror=implicit-function-declaration]
   19 |  const size_t str_len = strnlen(rtable, 100);
      |                         ^~~~~~~
      |                         strlen
/home/francisco/workspace/RIOT/build/pkg/libcsp/src/csp_rtable_stdio.c:26:15: error: implicit declaration of function 'strtok_r'; did you mean 'strtok'? [-Werror=implicit-function-declaration]
   26 |  char * str = strtok_r(rtable_copy, ",", &saveptr);
      |               ^~~~~~~~
      |               strtok
/home/francisco/workspace/RIOT/build/pkg/libcsp/src/csp_rtable_stdio.c:26:15: error: initialization of 'char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
/home/francisco/workspace/RIOT/build/pkg/libcsp/src/csp_rtable_stdio.c:59:7: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
   59 |   str = strtok_r(NULL, ",", &saveptr);
```

2022-04-19 21:39 UTC, johandc requested changes
This is not the proper way to solve this. It Essentialy overrides the c library settings. 

I feel like the solution should be to include string.h explicitly.

2022-04-20 07:05 UTC, fjmolinas commented
> I feel like the solution should be to include string.h explicitly.

That was the first thing I tried, but sadly it did not work, the same error persisted. I'll see if I find another solution.

2022-04-20 07:17 UTC, fjmolinas commented
> > I feel like the solution should be to include string.h explicitly.
> 
> That was the first thing I tried, but sadly it did not work, the same error persisted. I'll see if I find another solution.

AFAIK `strnlen` and `strtok_r` are not part of the C standard, so when compiling with `-std=99` you don't get them by default, in `c11` you get `strnlen_s` and `strtok_s` but it's not exactly the same.

So the question is whether the used functions should be compliant with ISO C or POSIX. If the first then a  possible fix would be to simply replace those used functions by `strlen` or `strtok`, if POSIX, then I can define `_POSIX_C_SOURCE` instead of `_DEFAULT_SOURCE` to get exactly what is missing.

This is quite contained anyway, so if the preferred status is what is preferred, I don't think it will be too much of an issue for me to simply patch this locally.

2022-04-20 07:42 UTC, fjmolinas commented
> So the question is whether the used functions should be compliant with ISO C or POSIX. If the first then a possible fix would be to simply replace those used functions by `strlen` or `strtok`, if POSIX, then I can define `_POSIX_C_SOURCE` instead of `_DEFAULT_SOURCE` to get exactly what is missing.

Would in this case need to be `#define _POSIX_C_SOURCE=200809L` https://man7.org/linux/man-pages/man3/strnlen.3.html

2022-04-21 08:25 UTC, closed without merging