Nomtu, crc32 on connless, CSP 1 L2 broadcast + buffer leak fix, UDP interface single socket
libcsp/libcsp pull request #391
Opened 2022-11-12 10:35 UTC by johandc

Hello Instead of creating 4 pull requests and merging in order, i have joined our current development tree into a single PR.

- Adressing #390 i have decided to remove the iface->mtu field, and go with a simpler approach. Please read the commit message for that change.
- CRC32 is now required on incoming connection-less packets. Usually it is the one who calls csp_connect or csp_socket, who sets the options. But for connection-less (callback pattern) messages the options was set to 0x0, which meant any it was accepting garbage data as valid csp packets occasionally. If there is no higher layer check (csp_ping, poke and peek for example has none) it could mean writing data to memory at arbitrary memory fields. So this was a security concern that is mitigated by requiring CRC32 to be valid on all connection-less incoming packets. As a consequence, a csp_ping, peek poke 
client functions have added csp_o_crc32.
- CSP 1 supports CAN broadcast on address 31 now
- One buffer leak and one null pointer check have been fixed.
- The UDP interface have been modified slightly, so instead of using two different sockets (one for each direction) it uses a single socket. This makes it compatible with the satlab implementation of csp_if_udp (https://github.com/satlab/libcsp/blob/satlab-master/src/interfaces/csp_if_sludp.c) which eventually could get jointed into master.

2022-11-12 10:59 UTC, johandc commented
Also include the changes from Taylor's fix of https://github.com/libcsp/libcsp/issues/385.

csp buffer get now explicitly returns a csp packet, and the size field has been renamed and the documentation changed to show that the size field is no longer used.

2022-11-13 15:02 UTC, yashi reviewed
just a quick review.  I'll review more in the coming week.

2022-11-13 15:02 UTC, yashi commented on src/interfaces/csp_if_kiss.c
> +		if (&ifdata->rx_packet->frame_begin[ifdata->rx_length] >= &ifdata->rx_packet->data[sizeof(ifdata->rx_packet->data)]) {
Why do you have to replace `rx_length` with the pointer arithmetic?

Is this fixing a bug not considering the header size in the original?  If so, we should fix it in another commit or at least add a comment in the commit log.

2022-11-13 15:43 UTC, johandc commented on src/interfaces/csp_if_kiss.c
> +		if (&ifdata->rx_packet->frame_begin[ifdata->rx_length] >= &ifdata->rx_packet->data[sizeof(ifdata->rx_packet->data)]) {
Understood one is looking more nice in this context.
But bear in mind that somewhere the max_rx_length parameter needs to be set.  So we are deleting a variable, and a place for the programmer to make an error.
The pointer arithmetic checks that the actual write address does not exceed the length of the actual packet allocation. It looks meesy, and maybe we could make it look nicer by adding a middle compile time defined const.

const int max_rx_length = sizeof(packet->data) + csp header length.

However, the last part of the header length is a variable. So ill take that back again.

If you can find a prettier method to check the overflow, without adding a variable to the data structure, or god forbid, another MTU field. You are very welcome to do so. 

I actually just considered adding a single sentinel byte to the end of the packet_t structure, which was easy to just take the address of for frame_end comparisons. What do you think about that? Furthermore we could set it to a known good sentinel value 0x5A for example, and check for buffer overflows on buffer_free too.

2022-12-06 07:57 UTC, yashi requested changes
Sorry to be late.  I've review a few additional commits.   The biggest issue I've found is that using a valid file descriptor `0` as an error state.  Did I miss your intention?

2022-12-06 07:57 UTC, yashi commented on src/csp_yaml.c
> +		printf("  ERROR: failed to find CSP config file\n");
it may not be an issue but should we use `csp_print()` instead?

2022-12-06 07:57 UTC, yashi commented on src/interfaces/csp_if_udp.c
> +		return CSP_ERR_NONE;
Why are you freeing the packet when `sockfd` is 0?  `socket()` returns a negative for errors, and 0 and positive for valid file descriptors.

2022-12-06 07:57 UTC, yashi commented on src/interfaces/csp_if_udp.c
> -	struct sockaddr_in server_addr = {0};
No need to initialize as `0`.  We are initializing all three members, `sin_family`, `sin_port`, and `sin_addr`, right after this.

2022-12-06 07:57 UTC, yashi commented on src/interfaces/csp_if_udp.c
> +		if (ifconf->sockfd < 0) {
too late to test it.  If we test, test it after `socket()`.     If we want to, we should test the return value of `bind()` here instead of `ifconf->sockfd`.  And make sure to `ifconf->sockfd = -1` when `bind()` failed`.   Otherwise, you leave the while loop.

2022-12-06 07:57 UTC, yashi commented on src/interfaces/csp_if_udp.c
> +		ifconf->sockfd = socket(AF_INET, SOCK_DGRAM, PF_PACKET);
Why using `PF_PACKET`?

2022-12-06 07:57 UTC, yashi commented on src/interfaces/csp_if_udp.c
>  			csp_print("  UDP server waiting for port %d\n", ifconf->lport);
The message is a bit bogus.  What do you mean by "waiting for port X"?   Are we waiting for the specified port to be available?  If so, we should be testing `bind()`.

With the current form, we are printing the message when `socket()` failed.

2022-12-06 07:57 UTC, yashi commented on src/interfaces/csp_if_udp.c
> +	while (ifconf->sockfd == 0) {
I think using a valid file descriptor as an error is wrong.

2022-12-06 07:57 UTC, yashi commented on src/csp_route.c
> +		if (csp_route_security_check(CSP_SO_CRC32REQ, input.iface, packet) < 0) {
It'd be nice if we add a commit message from the comment on this PR.

2022-12-06 09:56 UTC, yashi commented on src/arch/freertos/meson.build
> -	'csp_clock.c',
Don't you want to remove `src/arch/freertos/csp_clock.c` as well?

2022-12-06 09:56 UTC, yashi commented on src/interfaces/csp_if_can_pbuf.c
> +	csp_can_pbuf_cleanup(ifdata, task_woken);
Instead of passing `task_woken` to indicate that the call is from ISR or not, why not make `csp_get_ms()` callable from any context including ISR?

Or, does FreeRTOS have an unified API to test that it's in ISR or not?  I see `xPortIsInsideInterrupt` or `uxInterruptNesting` is used to test it.  But my FreeRTOS knowledge is limited.

Or, should we have `_isr()` variant of it?  We have two patterns for functions callable from ISR.  Functions with `_isr` suffix and additional argument `task_woken`.

2022-12-08 08:37 UTC, johandc commented on src/csp_yaml.c
> +		printf("  ERROR: failed to find CSP config file\n");
Well yes. Maybe i just got complacecent because yaml is only used on PCs anyways. But of course

2022-12-08 08:39 UTC, johandc commented on src/interfaces/csp_if_udp.c
> +		return CSP_ERR_NONE;
Good catch.

The major change is that the interface must not return ERR_BUSY, because we do not support blocking csp send anyways. So if the outgoing buffer is full, just discard the message, and rely on flow control to fix the issue.

2022-12-08 08:40 UTC, johandc commented on src/interfaces/csp_if_udp.c
> -	struct sockaddr_in server_addr = {0};
ok

2022-12-08 08:43 UTC, johandc commented on src/interfaces/csp_if_udp.c
> +		ifconf->sockfd = socket(AF_INET, SOCK_DGRAM, PF_PACKET);
Good question. I dont know. The major change in csp_if_udp came from syncing with the satlab implementation of the same interface. Maybe i got it from there, or maybe we already used PF_PACKET. As far as i can read from the MAN page, PF_PACKET is the type we want, so i dont think its wrong.

2022-12-08 08:45 UTC, johandc commented on src/interfaces/csp_if_udp.c
> +		if (ifconf->sockfd < 0) {
Okay

2022-12-08 08:46 UTC, johandc commented on src/interfaces/csp_if_udp.c
>  			csp_print("  UDP server waiting for port %d\n", ifconf->lport);
Okay. Yes. We should be waiting on bind. We hardly ever use this interface, so it has not seen much every day testing. So i have not run into this as an issue. But you are correct.

2022-12-08 08:53 UTC, johandc commented on src/arch/freertos/meson.build
> -	'csp_clock.c',
I dont know, what is your feeling about this change?

I had to mess with nasty static library include orders, because GCC has no concept of full scanning all included static libraries unless everything is linked with --link-whole. But this possesses other major problems. So i think i would like to get rid of __weak__ linking alltogether. If nobody talks me out of it??

2022-12-08 08:58 UTC, johandc commented on src/interfaces/csp_if_can_pbuf.c
> +	csp_can_pbuf_cleanup(ifdata, task_woken);
Its a bit messy indeed.

FreeRTOS does have functions to tell if we are inside an ISR. Which would be the cleanest method of making functions callabel from both contexts. However, FreeRTOS own API requires us to keep this TaskWoken parameter in userspace, instead of having an internal variable it checks when exiting the ISR. 

So the reason we follow this pattern is not to inform our own functions which API function to use. Its actually to do FreeRTOS dirty work, and moving the task_woken parameter with us all the way through. 

CSP was written on FreeRTOS first, so the implementation of their API has influenced the CSP api, so that we have _isr functions and stuff. So this is not related to this pull request itself. But we might want to create a separate issue to cleanup this leaky API some day.

2022-12-12 07:45 UTC, yashi commented on src/interfaces/csp_if_udp.c
> +		ifconf->sockfd = socket(AF_INET, SOCK_DGRAM, PF_PACKET);
correct me if I'm mistaken, but `socket(2)` takes protocol number as the third argument.  You don't specify `PF_PACKET` as the third.

If you want to use cooked UDP, use
```c
socket(AF_INET, SOCK_DGRAM, protonum);
```

If you want to use packet interface with raw packets, do
```c
socket(AF_PACKET, SOCK_RAW, protonum);
```

Or, if you want to use packet interface with cooked packet,
```c
socket(AF_PACKET, SOCK_DGRAM, protonum);
```

You can use `PF_` prefix instead of `AF_`, ie) `PF_INET` instead of `AF_INET`, or `PF_PACKET` instead of `AF_PACKET`.

2022-12-12 07:59 UTC, yashi commented on src/arch/freertos/meson.build
> -	'csp_clock.c',
Hm... I don't really have a problem with weak refs. Maybe that's because I rarely replace weak ref symbols on my system.  Or Zephyr build system is doing what I want to do.  Not sure.

Regarding `csp_clock_{get,set}_time()`, I'm totally fine removing the API as well.  We are not using it in the CSP stack at all.  These are just handy wrappers for POSIX `clock_gettime()`.

2023-09-09 11:09 UTC, merged