drivers, interfaces: Fixes for multiple security-relevant issues
libcsp/libcsp pull request #510
Opened 2024-01-31 11:51 UTC by pr0me

This PR introduces patches to multiple potentially security-relevant bugs
after a code review.

Issues:
- csp_if_can: a buffer overflow due to an off-by-one in an overflow check in the CAN interface
- can_socketcan: potential buffer overflows in the CAN interface due to unchecked size field in the raw incoming CAN frame
- usart_linux: using a pointer returned by malloc without checking for NULL
- usart_linux: memory leaks due to unfreed pointers and unclosed file descriptors in possible paths in the USART driver, fixed by early failing
- csp_if_udp: destroying (freeing) resources allocated within a pthread `attribute` after using them as defined by POSIX

This PR was developed in collaboration with @yashi

2024-02-01 13:10 UTC, yashi commented
- I have addressed Clang complaing about double parenthathese on `if` condition.
- Added some commit log to a few commits.  (more to come).

@pr0me, would you mind taking a look at the changes in `"drivers: usart: Return early when no callback or fd ptrs are provided; This also prevents memory leaks later on"`? I believe the original code allowed users not to provide a callback. I am confident that the usage is valid: if a user can obtain a file descriptor from the function, they can write their own function to read from the `fd`.

So, the only invalid case is when a user doesn't provide both `rx_callback` and `return_fd`.

WDYT?

2024-02-01 15:42 UTC, pr0me commented
Agreed, the original code allowed that @yashi 
As it was intended, I made changes to reflect this usage and still fail early if neither is provided while fixing the memory leaks.

Let me know what you think

2024-02-02 06:28 UTC, yashi requested changes

2024-02-02 06:28 UTC, yashi commented on src/drivers/usart/usart_linux.c
>  	}
Because we check `rx_callback` and `return_fd` at the very beginning of the function, we can now do something like:

```c
if (rx_callback) {
    ctx = calloc();
    ctx->rx_callback = rx_callback;
    ctx->fd = fd;
}

if (return_fd) {
    return_fd = fd;
}

return CS_ERROR_NONE;
```

Once we know we have either or both of `rx_callback` and `return_fd`, we are sure that `fd` won't be leaked. (Except for, of course, error cases)

IOW, we don't want to close the file when `rx_callback` expect to be open.

2024-02-02 12:03 UTC, pr0me commented on src/drivers/usart/usart_linux.c
>  	}
oh that's right, I've overlooked that rx_callback is using the open fd.
I've updated the commit accordingly

2024-02-04 09:56 UTC, yashi commented
@pr0me OK. I've updated all commit messages, and added one change I've found while reviewing them.  Please check them again.  If you are OK with it, I can merge this PR.

2024-02-04 11:10 UTC, pr0me commented
Changes and commit messages are looking great, especially the off-by-one error one, thanks for the effort!

Let's ship it

2024-02-04 13:43 UTC, merged