kiss: Add node_id parameter
libcsp/libcsp pull request #564
Opened 2024-04-26 01:46 UTC by moonlight83340

In the commit 0d4dac28a5bf75390bdd1ef26e1c109094e0a032, 
`csp_can_socketcan_open_and_add_interface()` gained new parameter node_id, which is assigned to ctx->iface.addr in the function. 
Add address / node_id parameter to `csp_usart_open_and_add_kiss_interface()`.

Fix https://github.com/libcsp/libcsp/issues/459

2024-04-29 06:26 UTC, yashi requested changes

2024-04-29 06:26 UTC, yashi commented on src/bindings/python/pycsp.c
> +	int res = csp_usart_open_and_add_kiss_interface(&conf, if_name, addr, NULL);
Does it mean `addr` is always `0`?  If so, is it what the users of python script want? I doubt that.

2024-04-29 06:26 UTC, yashi commented on include/csp/drivers/usart.h
> +int csp_usart_open_and_add_kiss_interface(const csp_usart_conf_t * conf, const char * ifname, uint16_t node_id, csp_iface_t ** return_iface);
I know we have been using `node_id` for an address for a node, but since we now have an address per interface can we use `addr` for all?  Each node might have muliple interfaces and thus multiple addresses.

2024-04-30 00:51 UTC, moonlight83340 commented on src/bindings/python/pycsp.c
> +	int res = csp_usart_open_and_add_kiss_interface(&conf, if_name, addr, NULL);
Sorry, now I pass the addr by argument !

2024-04-30 07:34 UTC, yashi requested changes

2024-04-30 07:34 UTC, yashi commented on src/bindings/python/pycsp.c
> +	int res = csp_usart_open_and_add_kiss_interface(&conf, if_name, addr, NULL);
Indeed you passed it but, are you sure we want:

- the arguments in that order?
- the address to be an optional arg?
- `I` instead of `H`.

Let's use `H` for now.  `unsigned short` is enough for 14 bits address.  Would you mind fixing `pycsp_can_socketcan_init`, which uses `i` instead, in a separate commit?

2024-04-30 07:34 UTC, yashi commented on src/drivers/usart/usart_kiss.c
> +int csp_usart_open_and_add_kiss_interface(const csp_usart_conf_t * conf, const char * ifname, uint16_t node_id, csp_iface_t ** return_iface) {
`s/node_id/addr/`

2024-04-30 07:36 UTC, moonlight83340 commented on src/bindings/python/pycsp.c
> +	int res = csp_usart_open_and_add_kiss_interface(&conf, if_name, addr, NULL);
Thank you, I will correct it !

2024-04-30 07:57 UTC, moonlight83340 commented on include/csp/drivers/usart.h
> +int csp_usart_open_and_add_kiss_interface(const csp_usart_conf_t * conf, const char * ifname, uint16_t node_id, csp_iface_t ** return_iface);
Would it mean to replace the `node_id` everywhere by `addr `?

2024-08-12 16:42 UTC, moonlight83340 commented
Rebase.

2024-08-12 16:46 UTC, moonlight83340 commented
ABI Compliance check fail because Parameter addr of type uint16_t has been added to `csp_usart_open_and_add_kiss_interface() `.
Please check the report for more informations.

2024-08-16 08:26 UTC, moonlight83340 commented
I forgot I changed parameters, I will correct that part !

2024-08-21 03:33 UTC, yashi commented
You need to work on the commit message a bit. It could be somehitng like:

> kiss: Add `addr` parameter
> 
> In commit 0d4dac2, we added a CSP address parameter to the
> `csp_can_socketcan_open_and_add_interface()` function. The address is
> assigned to `ctx->iface.addr`.
> 
> This commit similarly adds an `addr` parameter for the CSP address to
> `csp_usart_open_and_add_kiss_interface()`, allowing us to specify the
> address for the given interface.
>

2024-08-21 03:34 UTC, yashi commented
for the commit "examples: python: Add new parameters support to the examples", it has many logical changes.  Split them for each logical change.

2024-08-21 03:36 UTC, yashi commented on .github/workflows/build-test-python.yml
>            PYTHONPATH=builddir python3 examples/python_bindings_example_client.py -z localhost -s 27 -a 2
Can we use non-default values for these lines? So that we can check the parameter really works.

2024-08-21 06:14 UTC, yashi commented on src/bindings/python/pycsp.c
> +	uint16_t addr = 0;
Why do you initialize `addr` to `0`?

2024-08-21 06:17 UTC, moonlight83340 commented on src/bindings/python/pycsp.c
> +	uint16_t addr = 0;
because I saw that `pycsp_can_socketcan_init` was also doing it 😅

2024-08-22 00:03 UTC, yashi requested changes

2024-08-22 00:03 UTC, yashi commented on examples/python_bindings_example_client.py
Please leave trailing whitespace changes alone. I'd accept a few fixes but this commit adds too much noise.

2024-08-22 00:03 UTC, yashi commented on examples/python_bindings_example_server.py
> +    return parser.parse_args(sys.argv[1:])
Why did you need `sys.argv[1:]`?

2024-08-22 00:03 UTC, yashi commented on examples/python_bindings_example_client.py
missing commit message body.

2024-08-22 00:03 UTC, yashi commented on .github/workflows/build-test-python.yml
Add why you changed server address from 3 to 27 in the commit log.

2024-08-22 02:06 UTC, moonlight83340 commented on .github/workflows/build-test-python.yml
> I changed the address in zmq test to test the option parameter, introduce by this commit.

I added this part to explain why I have change the current default address.

2024-08-22 02:26 UTC, moonlight83340 commented on examples/python_bindings_example_server.py
> +    return parser.parse_args(sys.argv[1:])
No need indeed.

2024-08-22 02:31 UTC, moonlight83340 commented on .github/workflows/build-test-python.yml
*by previous commit.

2024-08-23 06:11 UTC, yashi approved these changes
It looks super nice. Thank you for your hard work.

2024-08-23 06:11 UTC, merged