RDP: Fix ACK unconditionally accepted via RST + ACK
libcsp/libcsp pull request #597
Opened 2024-06-28 16:18 UTC by moonlight83340

If a RST + ACK segment arrives in the OPEN state, the ACK was accepted unconditionally. 
Add a sequence number check to verify if the RST-ACK is out of sequence.

See issue https://github.com/libcsp/libcsp/issues/369

2024-08-12 17:09 UTC, moonlight83340 commented
Rebase.

2024-08-21 03:45 UTC, yashi commented on src/csp_rdp.c
> +			}else{
fix white space

2024-08-21 03:45 UTC, yashi commented on src/csp_rdp.c
> +				csp_rdp_protocol("RDP %p: RST ACK out of sequence, keep connection open\n", conn);
print received and expected sequence numbers

2024-08-21 07:09 UTC, yashi requested changes

2024-08-21 07:09 UTC, yashi commented on src/csp_rdp.c
> +				csp_rdp_protocol("RDP %p: RST ACK out of sequence, seq_nr : %d, expected seq_nr: %d,keep connection open\n", conn, rx_header->seq_nr, (conn->rdp.rcv_cur + 1));
the line is too long.  Move arguments to the next line.

2024-08-22 00:09 UTC, yashi commented
Please elaborate a bit more.

This is the original commit log:

> If a RST + ACK segment arrives in the OPEN state,
> the ACK was accepted unconditionally.
> Add a sequence number check to verify if the RST-ACK is out of sequence.

It doesn't say
- why it accept unconditionally
- why it's a bad thing

Also, 
- is "a RST + ACK segment" the same as "the ACK"? (what the old code does is `/* Store current ack'ed sequence number */`)
- With the commit, you only accept `rx_header->seq_nr == (conn->rdp.rcv_cur + 1)`, but what if order of the arriving packet is not sequential?

2024-08-22 00:10 UTC, yashi commented on src/csp_rdp.c
> +			if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
What if packets arrives non sequential order?

2024-08-22 02:41 UTC, moonlight83340 commented on src/csp_rdp.c
> +			if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
The RST will be ignored.

2024-08-22 03:26 UTC, yashi commented on src/csp_rdp.c
> +			if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
That's not acceptable, then.

2024-08-22 03:28 UTC, yashi commented on src/csp_rdp.c
> +			if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
Is it acceptable as RDP?

2024-08-22 06:44 UTC, moonlight83340 commented on src/csp_rdp.c
> +			if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
https://www.rfc-editor.org/rfc/rfc908
https://datatracker.ietf.org/doc/html/rfc1151

I haven't found in the RFC if it's acceptable or not to do so.
But I feel like the issue author, that we shouldn't accepted an RST ACK packet if the sequence number is unordered.

2024-08-23 07:45 UTC, yashi commented on src/csp_rdp.c
> +			if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
care to elaborate a bit more?

2024-09-18 15:35 UTC, closed without merging

2024-09-18 15:35 UTC, johandc commented
Hello, there is already a check on RST out of sequence, that sends to discard_open.

```
	/* If a RESET was received. */
	if (rx_header->flags & RDP_RST) {

		if (rx_header->flags & RDP_ACK) {
			/* Store current ack'ed sequence number */
			conn->rdp.snd_una = rx_header->ack_nr + 1;
		}

		if (conn->rdp.state == RDP_CLOSED) {
			csp_rdp_protocol("RDP %p: RST received in CLOSED - ignored\n", conn);
			close_connection = (conn->dest_socket != NULL);
			goto discard_open;
		}

		if (conn->rdp.state == RDP_CLOSE_WAIT) {
			csp_rdp_protocol("RDP %p: RST received in CLOSE_WAIT, ack: %d - closing\n", conn, (rx_header->flags & RDP_ACK));
			if ((rx_header->flags & RDP_ACK) && CSP_USE_RDP_FAST_CLOSE) {
				// skip timeout - the other end has acknowledged the RST
				closed_by |= CSP_RDP_CLOSED_BY_TIMEOUT;
			}
			goto discard_close;
		}

		if (rx_header->seq_nr == (conn->rdp.rcv_cur + 1)) {
			csp_rdp_protocol("RDP %p: Received RST in sequence, no more data incoming, reply with RST\n", conn);
			conn->rdp.state = RDP_CLOSE_WAIT;
			conn->timestamp = csp_get_ms();
			csp_rdp_send_cmp(conn, NULL, RDP_ACK | RDP_RST, conn->rdp.snd_nxt, conn->rdp.rcv_cur);
			if (CSP_USE_RDP_FAST_CLOSE) {
				closed_by |= CSP_RDP_CLOSED_BY_TIMEOUT;
			}
			goto discard_close;
		}

		csp_rdp_protocol("RDP %p: RST out of sequence, keep connection open\n", conn);
		goto discard_open;
	}
```

The ACK_NR field should always be unconditionally accepted. Because its conveying valid information on the stream in the other direction.