github: workflow: Add ABI Compliance Check
libcsp/libcsp pull request #631
Opened 2024-08-08 17:18 UTC by moonlight83340

I try to make a github workflow for ABI compliance check.
It's currently a WIP. I'm not used to make github workflow file so I wanted to share my first version 😅 
I saw it would be nice to do a github action from this issue https://github.com/libcsp/libcsp/issues/618

2024-08-08 23:16 UTC, yashi reviewed
Thanks! Looks good to me.

2024-08-08 23:16 UTC, yashi commented on .github/workflows/abi-checker.yml
> +            CXX: g++
not needed. unless you want to build it with clang.

2024-08-09 03:22 UTC, yashi requested changes

2024-08-09 03:22 UTC, yashi commented on .github/workflows/abi-checker.yml
> +          sudo apt-get install libzmq3-dev libsocketcan-dev socat
Why do you need socat

2024-08-09 03:22 UTC, yashi commented on .github/workflows/abi-checker.yml
> +        continue-on-error: true
What we need to know is that this PR introduce ABI change or not. So you have to compare against merge base instead of the stable branch.

2024-08-09 03:22 UTC, yashi commented on .github/workflows/abi-checker.yml
> +        continue-on-error: true
This means that we don't really need to run this on push, but need to check on all PRs.

2024-08-09 03:43 UTC, moonlight83340 commented on .github/workflows/abi-checker.yml
> +        continue-on-error: true
weird thing I get an error on checkout here but not on my own repository...
https://github.com/moonlight83340/libcsp/actions/runs/10313278326/job/28549781344?pr=1

2024-08-09 03:46 UTC, moonlight83340 commented on .github/workflows/abi-checker.yml
> +          sudo apt-get install libzmq3-dev libsocketcan-dev socat
No need indeed.

2024-08-09 04:01 UTC, yashi commented on .github/workflows/abi-checker.yml
> +        continue-on-error: true
where? I only see greens

![image](https://github.com/user-attachments/assets/e6dc6a23-8b2d-4850-8e91-5bd6de964e72)

2024-08-09 04:08 UTC, moonlight83340 commented on .github/workflows/abi-checker.yml
> +        continue-on-error: true
Nevermind I find out !

2024-08-09 07:39 UTC, yashi requested changes

2024-08-09 07:39 UTC, yashi commented on .github/workflows/abi-checker.yml
> +        continue-on-error: true
Why do you need this? If the following upload need to work independent from `abi-comliance-chcker`'s exit code, use `if: always()`.  You can also use `if-no-files-found`. Check the doc: https://github.com/actions/upload-artifact

Also please make it indicate that incompatible is found.

2024-08-12 00:50 UTC, yashi requested changes

2024-08-12 00:50 UTC, yashi commented on .github/workflows/abi-checker.yml
> +          sudo apt-get install -y abi-compliance-checker abi-dumper
Consistancy.  Remove `-y` to follow the same pattern from the above and the doc.

2024-08-12 00:50 UTC, yashi commented on .github/workflows/abi-checker.yml
> +          cmake -GNinja -B build -DCMAKE_BUILD_TYPE=Debug -DCSP_HAVE_LIBZMQ=1 -DCSP_USE_RTABLE=1 -DCMAKE_POSITION_INDEPENDENT_CODE=ON && ninja -C build
Why `DCSP_HAVE_LIBZMQ=1`? This is not user option

2024-08-12 07:33 UTC, merged

2024-08-12 07:33 UTC, yashi commented
Let's see how it goes.