Added function comments to the CSP Queue function create_static_queue
libcsp/libcsp pull request #653
Opened 2024-08-18 00:47 UTC by alexapostolu

The function create_static_queue does not appear on the libcsp docs, so I added comments to the function

2024-08-18 05:43 UTC, yashi requested changes
Thanks for the PR!

Unfortunately I have to ask you to fix your PR.

- I see that your PR has a merge commit. Please remove it.
- Your PR has two identical commits. Keep c6f95a344722c4d7bf45c587c5abf811068d3206 and drop 74788b1dc15ac04c4b2c286abff404304c38c1cd.
- As I noted on the commit, please do not change the format without a good reason.

Thanks,

2024-08-18 05:43 UTC, yashi commented on include/csp/arch/csp_queue.h
> +csp_queue_handle_t csp_queue_create_static(int length, size_t item_size, char *buffer, csp_static_queue_t *queue);
Do not change parameter format.

2024-08-18 15:43 UTC, alexapostolu commented
Thank you for your feedback, I have made the requested changes

2024-08-18 18:05 UTC, moonlight83340 commented
> Thank you for your feedback, I have made the requested changes

You should avoid using revert commit 😅 

First, drop your last commit (the revert one):
`git reset --hard 7590e10e072f376b00e14c94af1d40b5933defd3`

Then, modify the function parameter back:
`git add include/csp/arch/csp_queue.h `

Finally, amend and push:
`git commit --amend`
`git push --force`

This way, you'll keep only one commit.

2024-08-18 19:16 UTC, alexapostolu commented
Should I have used `git rebase -i` instead?

2024-08-18 21:36 UTC, yashi commented
You can squash them and keep the commit message of 7590e10e072f376b00e14c94af1d40b5933defd3

2024-08-19 13:28 UTC, alexapostolu commented
I fixed it, thank you

2024-08-20 06:02 UTC, merged