github: workflow: Add CAN interface testing
libcsp/libcsp pull request #670
Opened 2024-08-22 08:41 UTC by moonlight83340

Added steps to set up a virtual CAN (vcan0) interface in the CI environment. 
Included tests for the CAN interface using the `csp_server` and `csp_client` examples.
Ensured the CAN interface is correctly configured with `modprobe vcan`and `ip link add dev vcan0 type vcan`.
Implemented both server and client tests to validate CAN communication.

This change enables automated testing of the CAN interface within the CI pipeline, improving test coverage for CAN-related functionality.

2024-08-23 07:36 UTC, yashi requested changes

2024-08-23 07:36 UTC, yashi commented on .github/workflows/build-test.yml
> +          ip -br link show vcan0
This does not wait until the interface `vcan0` is up.

2024-08-23 17:54 UTC, moonlight83340 commented on .github/workflows/build-test.yml
> +          ip -br link show vcan0
I think it should be okay but if we want to be really sure we can do something like that : 
```
  while ! ip -br link show vcan0 | grep -q "UP"; do
    echo "Waiting for vcan0 to be up..."
    sleep 1
  done
  echo "vcan0 is up"
```

2024-08-24 14:31 UTC, yashi commented on .github/workflows/build-test.yml
> +          ip -br link show vcan0
It is **_NOT_** OK. If it were OK, you wouldn't have added `sleep 1` in the first place. How can you say it's OK? And I'm sure I want to make sure it doesn't fail from time to time. I'm the one who needs to re-run the failed tests and fix or maintain them.

2024-08-24 14:43 UTC, yashi commented on .github/workflows/build-test.yml
> +          ip -br link show vcan0
It is **_NOT_** OK. Making sure `vcan0` is up isn't about being "really sure"; it's a fundamental requirement for the system to function correctly. The use of `sleep 1` suggests that we already anticipate this being a common issue, so it's not about adding extra caution—it's about handling the normal, expected behavior of the system. We need to have a reliable way to ensure `vcan0` is up before proceeding because this is a basic necessity, not an optional step. As the one responsible for re-running failed tests and maintaining this, it's crucial to have this reliability built in.

2024-08-24 14:56 UTC, moonlight83340 commented on .github/workflows/build-test.yml
> +          ip -br link show vcan0
Okay, I understand. I will check some way to correctly handle the `vcan0 `up.

2024-08-26 09:17 UTC, yashi commented on .github/workflows/build-test.yml
> +          sudo apt-get install libzmq3-dev libsocketcan-dev socat iproute2 can-utils
What do you use `can-utils` for?

2024-08-26 09:51 UTC, moonlight83340 commented on .github/workflows/build-test.yml
> +          sudo apt-get install libzmq3-dev libsocketcan-dev socat iproute2 can-utils
Not used, thanks.

2024-08-26 10:05 UTC, yashi requested changes

2024-08-26 10:05 UTC, yashi commented on .github/workflows/build-test.yml
> +      - name: Set vcan0
ditto

2024-08-26 10:48 UTC, yashi approved these changes

2024-08-26 10:48 UTC, merged