examples: python: Add CAN interface testing to python example
libcsp/libcsp pull request #671
Opened 2024-08-23 07:21 UTC by moonlight83340

This PR aim to add the support of CAN interface testing in the python example.

- Add the command line option for can and CAN init on python server example.
- Remove some trailing white space before client modification (it's hard to saw change if I let the white space)
- Modify the CAN interface init in client to show up to the user how to configure CAN interface in python example.
- Add CAN interface test in the python github workflow

2024-08-23 07:43 UTC, yashi requested changes

2024-08-23 07:43 UTC, yashi commented on examples/python_bindings_example_client.py
> +        libcsp.can_socketcan_init(options.can, options.address, 1000000, 1)
You didn't say why you chose to use 1 Mbps and promiscuous mode

2024-08-23 07:53 UTC, moonlight83340 commented on examples/python_bindings_example_client.py
> +        libcsp.can_socketcan_init(options.can, options.address, 1000000, 1)
I wanted to test as much possible arguments.
I choose 1Mbs because it's the default value 😅 . ( And I'm quite not sure what I should test).

2024-08-26 05:03 UTC, yashi requested changes

2024-08-26 05:03 UTC, yashi commented on examples/python_bindings_example_client.py
> +        libcsp.can_socketcan_init(options.can, options.address, 1000000, 1)
If it's the default, leave it alone.

2024-08-26 05:03 UTC, yashi commented on .github/workflows/build-test-python.yml
> +          echo "vcan0 is up"
If somehow this failed, you are left alone without any message. Print a message _before_ waiting.

2024-08-26 05:03 UTC, yashi commented on .github/workflows/build-test-python.yml
> +          echo "vcan0 is up"
also, can you split `vcan` setup part from the test?

2024-08-26 05:03 UTC, yashi commented on examples/python_bindings_example_client.py
> +        libcsp.rtable_load("0/0 CAN")
do we need this?

2024-08-26 05:03 UTC, yashi commented on examples/python_bindings_example_server.py
> +        libcsp.rtable_load("0/0 CAN")
This mean that we always use rtable?

2024-08-26 07:51 UTC, yashi requested changes

2024-08-26 07:51 UTC, yashi commented on .github/workflows/build-test-python.yml
> +      - name: Set vcan0
Setup instead of Set

2024-08-27 05:54 UTC, moonlight83340 commented on examples/python_bindings_example_server.py
> +        libcsp.rtable_load("0/0 CAN")
In fact, at first, I thought it was mandatory to use rtable because of how the Python example was written. 
However, after reading your comment, I checked and found that there's currently a bug in the Python binding; the code doesn't work if rtable isn't used (we have to use rtable_load).
I will create a PR after this one to fix that problem.

2024-08-27 10:29 UTC, yashi reviewed
If you add two interfaces, what happens?

2025-07-24 06:34 UTC, moonlight83340 commented
I will close for now. I think https://github.com/libcsp/libcsp/pull/801 would be helpful to continue that python testing.

2025-07-24 06:34 UTC, closed without merging