usart_kiss: Handle return values of csp_kiss_add_interface
libcsp/libcsp pull request #677
Opened 2024-09-04 03:43 UTC by moonlight83340

Updated the code to handle the return values of both `csp_kiss_add_interface` and `csp_usart_open` to ensure proper error handling.

The function now checks if `csp_kiss_add_interface` and also `csp_usart_open`.

If both operations are successful, the interface is returned via `return_iface`.

This change ensures that errors in the interface addition or USART opening are correctly propagated and handled.

2024-09-05 02:58 UTC, yashi requested changes

2024-09-05 02:58 UTC, yashi commented on src/drivers/usart/usart_kiss.c
>  	}
Hmm... I don't see any code "to ensure proper error handling".  When `csp_usart_open()` failed do you leave added interface as is? how about allocated `ctx`?

2024-09-05 03:11 UTC, moonlight83340 commented on src/drivers/usart/usart_kiss.c
>  	}
okay, thanks nice catch. ctx is not free if open failed...
In my previous commit : https://github.com/libcsp/libcsp/commit/913fc1713a95d088d8ac0a5fa858fec8926d9ef2
I think I should also free the interface in case of failing...

2024-09-05 08:20 UTC, yashi requested changes

2024-09-05 08:20 UTC, yashi commented on src/drivers/usart/usart_kiss.c
>  	}
Please double check what need to be freed or closed.

2026-04-20 10:52 UTC, yashi commented
@moonlight83340 What was the state of this PR? Do I need to review or do I need to wait a bit more?

2026-04-21 01:13 UTC, moonlight83340 commented
> @moonlight83340 What was the state of this PR? Do I need to review or do I need to wait a bit more?

I think it was ready for review at the time but allow me some time to check it this week.

2026-05-14 17:13 UTC, closed without merging