csp_rdp: Fix invalid connection creation
libcsp/libcsp pull request #744
Opened 2024-11-25 05:50 UTC by dimitrovand

- Update SYN flag check to only pass if the SYN flag is explicitly set, aligning with how RDP is documented in RFC 908. Previously, SYN|ACK packets could be misinterpreted as SYN packets, causing incorrect interpretation of packet data as connection parameters. This issue could lead to excessive packet and connection allocation durations.
- Improve the return value of `csp_rdp_rx_queue_add` by replacing raw integers with error codes defined in `csp_error.h` for better consistency.
- Modify the return value check for `csp_conn_enqueue_packet` to compare against `CSP_ERR_NONE`, aligning with its usage of standard error codes.

2024-11-26 09:38 UTC, yashi commented
Please split to three commits. These are orthogonal to each other.

2024-11-26 09:38 UTC, yashi requested changes
Please split to three commits. These are orthogonal to each other.

2024-11-28 01:48 UTC, yashi reviewed
Just curious, we have so many `rx_header->flags & RDP_*` check in our code base. Do we need to fix them all?

2024-11-28 01:48 UTC, yashi commented on src/csp_rdp.c
> +			if (rx_header_flags != RDP_SYN) {
You said in the commit log:

> Update SYN flag check to only pass if the SYN flag is explicitly set,

But the change is, as you documented in the comment, to ignore the ephemeral data added by `csp_rdp_send_cmp()`, and make sure the flags has `RDP_SYN` and only `RDP_SYN`.  The word "explicitly" might not express your intention.

Given that, it might be better to say:

> Update SYN flag check to ensure only the RDP_SYN flag is set, aligning with the RDP specification in RFC 908.
The previous implementation allowed SYN|ACK packets to be misinterpreted as SYN packets, leading to incorrect handling of packet data as connection parameters.
The updated check masks out the upper bits of the flags field and requires an exact match with RDP_SYN.
This change prevents unintended connection creation, reducing excessive packet and connection allocation durations.

Also you might want to reference "5.1  Connection Establishment" in the RFC because in other part of the RFC, it reads:

```
       If SYN set
```

Which feels like the code does exactly the RFC says. (but wrong).

BTW, we have so many `rx_header->flags & RDP_*` checks in our code base, do we have to fix other places as well?

2024-11-29 05:31 UTC, dimitrovand commented on src/csp_rdp.c
> +			if (rx_header_flags != RDP_SYN) {
Not sure if there are other places.

2024-11-29 06:07 UTC, yashi approved these changes
Thanks. LGTM.

2024-11-29 08:00 UTC, merged