Apply the fixes to the following CVEs:
libcsp/libcsp pull request #81
Opened 2016-10-28 11:22 UTC by eyalitki

CVE 2016-8596, 2016-8597, 2016-8598

2016-11-13 23:10 UTC, johandc commented
Hi, thank you for your contribution.

Security has never been a real concern of libcsp, so it's nice to see somebody pick up on and find these errors. Jeppe and I will review these changes and merge them upstream as soon as possible.

2016-11-16 15:09 UTC, niklas88 commented on src/csp_services.c
> +		packet->data[(packet->length - 1) ? packet->length >= 1 : 0] = 0;
This line is pretty confusing. So according to [StackOverflow](http://stackoverflow.com/questions/7687403/is-the-true-result-of-or-defined) in C99 packet->length >= 1 is either 0 or 1, so this should never set the last byte to 0. Also why does the original code always write 1 past the end of data[] which this code still does for the packet->length == 0 case?

Shouldn't this be something like

   if(packet->length){
      packet->data[packet->length-1] = 0;
   }

2016-11-18 10:19 UTC, eyalitki commented on src/csp_services.c
> +		packet->data[(packet->length - 1) ? packet->length >= 1 : 0] = 0;
Indeed it seems that I had a typo in this line.
As some projects prefer one-line-checks I tried to write the fix in a single line, and it does seems to be too complicated.
The fix you suggest is much cleaner, and it will do the trick for this specific problem.

Should mention though that this code fix is the minor part of the overall patch, as the rest of the fixes address major security issues (as listed in the above CVE list).

2017-04-10 08:46 UTC, jledet requested changes
I have added a couple of review comments.

2017-04-10 08:46 UTC, jledet commented on src/csp_route.c
> +			csp_log_error("Too short packet for XTEA, %u", packet->length);
Agree with this, but we should return CSP_ERR_XTEA and increment autherr here.

2017-04-10 08:46 UTC, jledet commented on src/csp_route.c
> +#ifdef CSP_USE_CRC32
Agree, we need a check for length >= 4 if CSP_FCRC32 is set. If not we should drop the packet (and not just print an error message).

2017-04-10 08:46 UTC, jledet commented on src/csp_services.c
> +		packet->data[(packet->length - 1) ? packet->length >= 1 : 0] = 0;
Agree with @niklas88 code.

2017-04-10 08:46 UTC, jledet commented on src/interfaces/csp_if_can.c
> +		}
Agree.

2017-04-10 08:46 UTC, jledet commented on src/interfaces/csp_if_zmqhub.c
> +
Also agree with this check, but I think it should be merged with the check for short frames (datalen < 5). Since datalen includes the 4 byte CSP header and a 1 byte "satid", the maximum length is also 261 bytes I think the ZMQ interface could use a cleanup and a comment to explain the protocol.

@johandc, is the `while(zmq_msg_recv(&msg, subscriber, ZMQ_NOBLOCK) > 0)` needed? It is calling `zmq_msg_close()` in a loop, but it is difficult to tell whether this is intentional or not as `zmq_msg_close()` is not indented. If the CSP packet allocation fails, `zmq_msg_close()` is just called directly.

2017-04-10 08:46 UTC, jledet commented on src/csp_sfp.c
> +
Agree.

2017-04-10 08:46 UTC, jledet commented on src/csp_sfp.c
> +		/* Comapre the data output to be consistent */
Compare

2017-04-10 08:46 UTC, jledet commented on src/csp_sfp.c
> +		else if ( *datasize != sfp_header->totalsize) {
Leading space in `if()`

2017-04-10 08:46 UTC, jledet commented on src/csp_sfp.c
> +		if (sfp_header->offset + packet->length == sfp_header->totalsize) {
Why not keep the `>=`?

2017-04-11 09:27 UTC, perwulff commented on src/csp_sfp.c
> +		if (sfp_header->offset + packet->length == sfp_header->totalsize) {
Agree, keep it.

2017-04-19 12:27 UTC, johandc commented on src/interfaces/csp_if_zmqhub.c
> +
The reason why it is there in the first place is that if (datalen < 5) there must be some kind of syncronization error. The only way to recover is to empty the entire buffer and hope that is itself will not create a new syncronization error, which is actually likely.

As Jeppe may remember this became a notorious problem on GOMX-3's ground station. Somehow data got stuck in the stream and never emptied out. This meant that sometimes packets were delayed by one. Which gave some pretty weird operating behaviour. For example. A ping message may go through only after the second ping is transmitted.

I don't understand why libzmq did this in the first place. I belive they had some bug that was fixed at a point, perhaps just not on our old groundstation.

Anyways. As you say we should group both min and max length checks into one check. Usually if this happens it's because of some kind of protocol sync error.

2020-01-08 10:16 UTC, perwulff commented
Again, thank you for your contribution.
 All the issues and a number of additional issues have been resolved in #129

2020-01-08 10:16 UTC, closed without merging